//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.14 at 10:23:17 AM UYST 
//


package uy.gub.dgi.cfe;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.w3._2000._09.xmldsig.SignatureType;

import uy.gub.dgi.cfe.CFEDefTypeX.EFactX;


/**
 * Comprobante Fiscal Electronico
 * 
 * <p>Java class for CFEDefType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CFEDefType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="eTck">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="TmstFirma" type="{http://cfe.dgi.gub.uy}FechaHoraType"/>
 *                     &lt;element name="Encabezado">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="IdDoc" type="{http://cfe.dgi.gub.uy}IdDoc_Tck"/>
 *                               &lt;element name="Emisor" type="{http://cfe.dgi.gub.uy}Emisor"/>
 *                               &lt;element name="Receptor" type="{http://cfe.dgi.gub.uy}Receptor_Tck" minOccurs="0"/>
 *                               &lt;element name="Totales" type="{http://cfe.dgi.gub.uy}Totales"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="Detalle">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="Item" type="{http://cfe.dgi.gub.uy}Item_Det_Fact" maxOccurs="700"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="SubTotInfo" type="{http://cfe.dgi.gub.uy}SubTotInfo" minOccurs="0"/>
 *                     &lt;element name="DscRcgGlobal" type="{http://cfe.dgi.gub.uy}DscRcgGlobal" minOccurs="0"/>
 *                     &lt;element name="MediosPago" type="{http://cfe.dgi.gub.uy}MediosPago" minOccurs="0"/>
 *                     &lt;element name="Referencia" type="{http://cfe.dgi.gub.uy}Referencia" minOccurs="0"/>
 *                     &lt;element name="CAEData" type="{http://cfe.dgi.gub.uy}CAEDataType"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="eFact">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="TmstFirma" type="{http://cfe.dgi.gub.uy}FechaHoraType"/>
 *                     &lt;element name="Encabezado">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="IdDoc" type="{http://cfe.dgi.gub.uy}IdDoc_Fact"/>
 *                               &lt;element name="Emisor" type="{http://cfe.dgi.gub.uy}Emisor"/>
 *                               &lt;element name="Receptor" type="{http://cfe.dgi.gub.uy}Receptor_Fact"/>
 *                               &lt;element name="Totales" type="{http://cfe.dgi.gub.uy}Totales"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="Detalle">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="Item" type="{http://cfe.dgi.gub.uy}Item_Det_Fact" maxOccurs="200"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="SubTotInfo" type="{http://cfe.dgi.gub.uy}SubTotInfo" minOccurs="0"/>
 *                     &lt;element name="DscRcgGlobal" type="{http://cfe.dgi.gub.uy}DscRcgGlobal" minOccurs="0"/>
 *                     &lt;element name="MediosPago" type="{http://cfe.dgi.gub.uy}MediosPago" minOccurs="0"/>
 *                     &lt;element name="Referencia" type="{http://cfe.dgi.gub.uy}Referencia" minOccurs="0"/>
 *                     &lt;element name="CAEData" type="{http://cfe.dgi.gub.uy}CAEDataType"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="eRem">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="TmstFirma" type="{http://cfe.dgi.gub.uy}FechaHoraType"/>
 *                     &lt;element name="Encabezado">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="IdDoc" type="{http://cfe.dgi.gub.uy}IdDoc_Rem"/>
 *                               &lt;element name="Emisor" type="{http://cfe.dgi.gub.uy}Emisor"/>
 *                               &lt;element name="Receptor" type="{http://cfe.dgi.gub.uy}Receptor_Rem"/>
 *                               &lt;element name="Totales">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;element name="CantLinDet">
 *                                           &lt;simpleType>
 *                                             &lt;restriction base="{http://cfe.dgi.gub.uy}LineasDetType">
 *                                               &lt;totalDigits value="3"/>
 *                                               &lt;fractionDigits value="0"/>
 *                                               &lt;maxInclusive value="200"/>
 *                                             &lt;/restriction>
 *                                           &lt;/simpleType>
 *                                         &lt;/element>
 *                                       &lt;/sequence>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="Detalle">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="Item" type="{http://cfe.dgi.gub.uy}Item_Rem" maxOccurs="200"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="SubTotInfo" type="{http://cfe.dgi.gub.uy}SubTotInfo" minOccurs="0"/>
 *                     &lt;element name="Referencia" type="{http://cfe.dgi.gub.uy}Referencia" minOccurs="0"/>
 *                     &lt;element name="CAEData" type="{http://cfe.dgi.gub.uy}CAEDataType"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="eResg">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="TmstFirma" type="{http://cfe.dgi.gub.uy}FechaHoraType"/>
 *                     &lt;element name="Encabezado">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="IdDoc" type="{http://cfe.dgi.gub.uy}IdDoc_Resg"/>
 *                               &lt;element name="Emisor" type="{http://cfe.dgi.gub.uy}Emisor"/>
 *                               &lt;element name="Receptor" type="{http://cfe.dgi.gub.uy}Receptor_Resg"/>
 *                               &lt;element name="Totales" type="{http://cfe.dgi.gub.uy}Totales_Resg"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="Detalle">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="Item" type="{http://cfe.dgi.gub.uy}Item_Resg" maxOccurs="200"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="SubTotInfo" type="{http://cfe.dgi.gub.uy}SubTotInfo" minOccurs="0"/>
 *                     &lt;element name="Referencia" type="{http://cfe.dgi.gub.uy}Referencia" minOccurs="0"/>
 *                     &lt;element name="CAEData" type="{http://cfe.dgi.gub.uy}CAEDataType"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" fixed="1.0">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="3"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CFEDefType", propOrder = {
    "eTck",
    "eFact",
    "eRem",
    "eResg",
    "signature"
})

@XmlRootElement(name = "CFE")
public class CFEDefType {

    protected CFEDefType.ETck eTck;
    protected CFEDefType.EFact eFact;
    protected CFEDefType.ERem eRem;
    protected CFEDefType.EResg eResg;
    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#", required = true)
    protected SignatureType signature;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the eTck property.
     * 
     * @return
     *     possible object is
     *     {@link CFEDefType.ETck }
     *     
     */
    public CFEDefType.ETck getETck() {
        return eTck;
    }

    /**
     * Sets the value of the eTck property.
     * 
     * @param value
     *     allowed object is
     *     {@link CFEDefType.ETck }
     *     
     */
    public void setETck(CFEDefType.ETck value) {
        this.eTck = value;
    }

    /**
     * Gets the value of the eFact property.
     * 
     * @return
     *     possible object is
     *     {@link CFEDefType.EFact }
     *     
     */
    public CFEDefType.EFact getEFact() {
        return eFact;
    }

    /**
     * Sets the value of the eFact property.
     * 
     * @param value
     *     allowed object is
     *     {@link CFEDefType.EFact }
     *     
     */
    public void setEFact(CFEDefType.EFact value) {
        this.eFact = value;
    }

    /**
     * Gets the value of the eRem property.
     * 
     * @return
     *     possible object is
     *     {@link CFEDefType.ERem }
     *     
     */
    public CFEDefType.ERem getERem() {
        return eRem;
    }

    /**
     * Sets the value of the eRem property.
     * 
     * @param value
     *     allowed object is
     *     {@link CFEDefType.ERem }
     *     
     */
    public void setERem(CFEDefType.ERem value) {
        this.eRem = value;
    }

    /**
     * Gets the value of the eResg property.
     * 
     * @return
     *     possible object is
     *     {@link CFEDefType.EResg }
     *     
     */
    public CFEDefType.EResg getEResg() {
        return eResg;
    }

    /**
     * Sets the value of the eResg property.
     * 
     * @param value
     *     allowed object is
     *     {@link CFEDefType.EResg }
     *     
     */
    public void setEResg(CFEDefType.EResg value) {
        this.eResg = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TmstFirma" type="{http://cfe.dgi.gub.uy}FechaHoraType"/>
     *         &lt;element name="Encabezado">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="IdDoc" type="{http://cfe.dgi.gub.uy}IdDoc_Fact"/>
     *                   &lt;element name="Emisor" type="{http://cfe.dgi.gub.uy}Emisor"/>
     *                   &lt;element name="Receptor" type="{http://cfe.dgi.gub.uy}Receptor_Fact"/>
     *                   &lt;element name="Totales" type="{http://cfe.dgi.gub.uy}Totales"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Detalle">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Item" type="{http://cfe.dgi.gub.uy}Item_Det_Fact" maxOccurs="200"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="SubTotInfo" type="{http://cfe.dgi.gub.uy}SubTotInfo" minOccurs="0"/>
     *         &lt;element name="DscRcgGlobal" type="{http://cfe.dgi.gub.uy}DscRcgGlobal" minOccurs="0"/>
     *         &lt;element name="MediosPago" type="{http://cfe.dgi.gub.uy}MediosPago" minOccurs="0"/>
     *         &lt;element name="Referencia" type="{http://cfe.dgi.gub.uy}Referencia" minOccurs="0"/>
     *         &lt;element name="CAEData" type="{http://cfe.dgi.gub.uy}CAEDataType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tmstFirma",
        "encabezado",
        "detalle",
        "subTotInfo",
        "dscRcgGlobal",
        "mediosPago",
        "referencia",
        "caeData"
    })
    public static class EFact {

        @XmlElement(name = "TmstFirma", required = true)
        protected XMLGregorianCalendar tmstFirma;
        @XmlElement(name = "Encabezado", required = true)
        protected CFEDefType.EFact.Encabezado encabezado;
        @XmlElement(name = "Detalle", required = true)
        protected CFEDefType.EFact.Detalle detalle;
        @XmlElement(name = "SubTotInfo")
        protected SubTotInfo subTotInfo;
        @XmlElement(name = "DscRcgGlobal")
        protected DscRcgGlobal dscRcgGlobal;
        @XmlElement(name = "MediosPago")
        protected MediosPago mediosPago;
        @XmlElement(name = "Referencia")
        protected Referencia referencia;
        @XmlElement(name = "CAEData", required = true)
        protected CAEDataType caeData;

        /**
         * Gets the value of the tmstFirma property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTmstFirma() {
            return tmstFirma;
        }

        /**
         * Sets the value of the tmstFirma property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTmstFirma(XMLGregorianCalendar value) {
            this.tmstFirma = value;
        }

        /**
         * Gets the value of the encabezado property.
         * 
         * @return
         *     possible object is
         *     {@link CFEDefType.EFact.Encabezado }
         *     
         */
        public CFEDefType.EFact.Encabezado getEncabezado() {
            return encabezado;
        }

        /**
         * Sets the value of the encabezado property.
         * 
         * @param value
         *     allowed object is
         *     {@link CFEDefType.EFact.Encabezado }
         *     
         */
        public void setEncabezado(CFEDefType.EFact.Encabezado value) {
            this.encabezado = value;
        }

        /**
         * Gets the value of the detalle property.
         * 
         * @return
         *     possible object is
         *     {@link CFEDefType.EFact.Detalle }
         *     
         */
        public CFEDefType.EFact.Detalle getDetalle() {
            return detalle;
        }

        /**
         * Sets the value of the detalle property.
         * 
         * @param value
         *     allowed object is
         *     {@link CFEDefType.EFact.Detalle }
         *     
         */
        public void setDetalle(CFEDefType.EFact.Detalle value) {
            this.detalle = value;
        }

        /**
         * Gets the value of the subTotInfo property.
         * 
         * @return
         *     possible object is
         *     {@link SubTotInfo }
         *     
         */
        public SubTotInfo getSubTotInfo() {
            return subTotInfo;
        }

        /**
         * Sets the value of the subTotInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link SubTotInfo }
         *     
         */
        public void setSubTotInfo(SubTotInfo value) {
            this.subTotInfo = value;
        }

        /**
         * Gets the value of the dscRcgGlobal property.
         * 
         * @return
         *     possible object is
         *     {@link DscRcgGlobal }
         *     
         */
        public DscRcgGlobal getDscRcgGlobal() {
            return dscRcgGlobal;
        }

        /**
         * Sets the value of the dscRcgGlobal property.
         * 
         * @param value
         *     allowed object is
         *     {@link DscRcgGlobal }
         *     
         */
        public void setDscRcgGlobal(DscRcgGlobal value) {
            this.dscRcgGlobal = value;
        }

        /**
         * Gets the value of the mediosPago property.
         * 
         * @return
         *     possible object is
         *     {@link MediosPago }
         *     
         */
        public MediosPago getMediosPago() {
            return mediosPago;
        }

        /**
         * Sets the value of the mediosPago property.
         * 
         * @param value
         *     allowed object is
         *     {@link MediosPago }
         *     
         */
        public void setMediosPago(MediosPago value) {
            this.mediosPago = value;
        }

        /**
         * Gets the value of the referencia property.
         * 
         * @return
         *     possible object is
         *     {@link Referencia }
         *     
         */
        public Referencia getReferencia() {
            return referencia;
        }

        /**
         * Sets the value of the referencia property.
         * 
         * @param value
         *     allowed object is
         *     {@link Referencia }
         *     
         */
        public void setReferencia(Referencia value) {
            this.referencia = value;
        }

        /**
         * Gets the value of the caeData property.
         * 
         * @return
         *     possible object is
         *     {@link CAEDataType }
         *     
         */
        public CAEDataType getCAEData() {
            return caeData;
        }

        /**
         * Sets the value of the caeData property.
         * 
         * @param value
         *     allowed object is
         *     {@link CAEDataType }
         *     
         */
        public void setCAEData(CAEDataType value) {
            this.caeData = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Item" type="{http://cfe.dgi.gub.uy}Item_Det_Fact" maxOccurs="200"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "item"
        })
        public static class Detalle {

            @XmlElement(name = "Item", required = true)
            protected List<ItemDetFact> item;

            /**
             * Gets the value of the item property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the item property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getItem().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ItemDetFact }
             * 
             * 
             */
            public List<ItemDetFact> getItem() {
                if (item == null) {
                    item = new ArrayList<ItemDetFact>();
                }
                return this.item;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="IdDoc" type="{http://cfe.dgi.gub.uy}IdDoc_Fact"/>
         *         &lt;element name="Emisor" type="{http://cfe.dgi.gub.uy}Emisor"/>
         *         &lt;element name="Receptor" type="{http://cfe.dgi.gub.uy}Receptor_Fact"/>
         *         &lt;element name="Totales" type="{http://cfe.dgi.gub.uy}Totales"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "idDoc",
            "emisor",
            "receptor",
            "totales"
        })
        public static class Encabezado {

            @XmlElement(name = "IdDoc", required = true)
            protected IdDocFact idDoc;
            @XmlElement(name = "Emisor", required = true)
            protected Emisor emisor;
            @XmlElement(name = "Receptor", required = true)
            protected ReceptorFact receptor;
            @XmlElement(name = "Totales", required = true)
            protected uy.gub.dgi.cfe.Totales totales;

            /**
             * Gets the value of the idDoc property.
             * 
             * @return
             *     possible object is
             *     {@link IdDocFact }
             *     
             */
            public IdDocFact getIdDoc() {
                return idDoc;
            }

            /**
             * Sets the value of the idDoc property.
             * 
             * @param value
             *     allowed object is
             *     {@link IdDocFact }
             *     
             */
            public void setIdDoc(IdDocFact value) {
                this.idDoc = value;
            }

            /**
             * Gets the value of the emisor property.
             * 
             * @return
             *     possible object is
             *     {@link Emisor }
             *     
             */
            public Emisor getEmisor() {
                return emisor;
            }

            /**
             * Sets the value of the emisor property.
             * 
             * @param value
             *     allowed object is
             *     {@link Emisor }
             *     
             */
            public void setEmisor(Emisor value) {
                this.emisor = value;
            }

            /**
             * Gets the value of the receptor property.
             * 
             * @return
             *     possible object is
             *     {@link ReceptorFact }
             *     
             */
            public ReceptorFact getReceptor() {
                return receptor;
            }

            /**
             * Sets the value of the receptor property.
             * 
             * @param value
             *     allowed object is
             *     {@link ReceptorFact }
             *     
             */
            public void setReceptor(ReceptorFact value) {
                this.receptor = value;
            }

            /**
             * Gets the value of the totales property.
             * 
             * @return
             *     possible object is
             *     {@link uy.gub.dgi.cfe.Totales }
             *     
             */
            public uy.gub.dgi.cfe.Totales getTotales() {
                return totales;
            }

            /**
             * Sets the value of the totales property.
             * 
             * @param value
             *     allowed object is
             *     {@link uy.gub.dgi.cfe.Totales }
             *     
             */
            public void setTotales(uy.gub.dgi.cfe.Totales value) {
                this.totales = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TmstFirma" type="{http://cfe.dgi.gub.uy}FechaHoraType"/>
     *         &lt;element name="Encabezado">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="IdDoc" type="{http://cfe.dgi.gub.uy}IdDoc_Rem"/>
     *                   &lt;element name="Emisor" type="{http://cfe.dgi.gub.uy}Emisor"/>
     *                   &lt;element name="Receptor" type="{http://cfe.dgi.gub.uy}Receptor_Rem"/>
     *                   &lt;element name="Totales">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="CantLinDet">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://cfe.dgi.gub.uy}LineasDetType">
     *                                   &lt;totalDigits value="3"/>
     *                                   &lt;fractionDigits value="0"/>
     *                                   &lt;maxInclusive value="200"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Detalle">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Item" type="{http://cfe.dgi.gub.uy}Item_Rem" maxOccurs="200"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="SubTotInfo" type="{http://cfe.dgi.gub.uy}SubTotInfo" minOccurs="0"/>
     *         &lt;element name="Referencia" type="{http://cfe.dgi.gub.uy}Referencia" minOccurs="0"/>
     *         &lt;element name="CAEData" type="{http://cfe.dgi.gub.uy}CAEDataType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tmstFirma",
        "encabezado",
        "detalle",
        "subTotInfo",
        "referencia",
        "caeData"
    })
    public static class ERem {

        @XmlElement(name = "TmstFirma", required = true)
        protected XMLGregorianCalendar tmstFirma;
        @XmlElement(name = "Encabezado", required = true)
        protected CFEDefType.ERem.Encabezado encabezado;
        @XmlElement(name = "Detalle", required = true)
        protected CFEDefType.ERem.Detalle detalle;
        @XmlElement(name = "SubTotInfo")
        protected SubTotInfo subTotInfo;
        @XmlElement(name = "Referencia")
        protected Referencia referencia;
        @XmlElement(name = "CAEData", required = true)
        protected CAEDataType caeData;

        /**
         * Gets the value of the tmstFirma property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTmstFirma() {
            return tmstFirma;
        }

        /**
         * Sets the value of the tmstFirma property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTmstFirma(XMLGregorianCalendar value) {
            this.tmstFirma = value;
        }

        /**
         * Gets the value of the encabezado property.
         * 
         * @return
         *     possible object is
         *     {@link CFEDefType.ERem.Encabezado }
         *     
         */
        public CFEDefType.ERem.Encabezado getEncabezado() {
            return encabezado;
        }

        /**
         * Sets the value of the encabezado property.
         * 
         * @param value
         *     allowed object is
         *     {@link CFEDefType.ERem.Encabezado }
         *     
         */
        public void setEncabezado(CFEDefType.ERem.Encabezado value) {
            this.encabezado = value;
        }

        /**
         * Gets the value of the detalle property.
         * 
         * @return
         *     possible object is
         *     {@link CFEDefType.ERem.Detalle }
         *     
         */
        public CFEDefType.ERem.Detalle getDetalle() {
            return detalle;
        }

        /**
         * Sets the value of the detalle property.
         * 
         * @param value
         *     allowed object is
         *     {@link CFEDefType.ERem.Detalle }
         *     
         */
        public void setDetalle(CFEDefType.ERem.Detalle value) {
            this.detalle = value;
        }

        /**
         * Gets the value of the subTotInfo property.
         * 
         * @return
         *     possible object is
         *     {@link SubTotInfo }
         *     
         */
        public SubTotInfo getSubTotInfo() {
            return subTotInfo;
        }

        /**
         * Sets the value of the subTotInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link SubTotInfo }
         *     
         */
        public void setSubTotInfo(SubTotInfo value) {
            this.subTotInfo = value;
        }

        /**
         * Gets the value of the referencia property.
         * 
         * @return
         *     possible object is
         *     {@link Referencia }
         *     
         */
        public Referencia getReferencia() {
            return referencia;
        }

        /**
         * Sets the value of the referencia property.
         * 
         * @param value
         *     allowed object is
         *     {@link Referencia }
         *     
         */
        public void setReferencia(Referencia value) {
            this.referencia = value;
        }

        /**
         * Gets the value of the caeData property.
         * 
         * @return
         *     possible object is
         *     {@link CAEDataType }
         *     
         */
        public CAEDataType getCAEData() {
            return caeData;
        }

        /**
         * Sets the value of the caeData property.
         * 
         * @param value
         *     allowed object is
         *     {@link CAEDataType }
         *     
         */
        public void setCAEData(CAEDataType value) {
            this.caeData = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Item" type="{http://cfe.dgi.gub.uy}Item_Rem" maxOccurs="200"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "item"
        })
        public static class Detalle {

            @XmlElement(name = "Item", required = true)
            protected List<ItemRem> item;

            /**
             * Gets the value of the item property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the item property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getItem().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ItemRem }
             * 
             * 
             */
            public List<ItemRem> getItem() {
                if (item == null) {
                    item = new ArrayList<ItemRem>();
                }
                return this.item;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="IdDoc" type="{http://cfe.dgi.gub.uy}IdDoc_Rem"/>
         *         &lt;element name="Emisor" type="{http://cfe.dgi.gub.uy}Emisor"/>
         *         &lt;element name="Receptor" type="{http://cfe.dgi.gub.uy}Receptor_Rem"/>
         *         &lt;element name="Totales">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="CantLinDet">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://cfe.dgi.gub.uy}LineasDetType">
         *                         &lt;totalDigits value="3"/>
         *                         &lt;fractionDigits value="0"/>
         *                         &lt;maxInclusive value="200"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "idDoc",
            "emisor",
            "receptor",
            "totales"
        })
        public static class Encabezado {

            @XmlElement(name = "IdDoc", required = true)
            protected IdDocRem idDoc;
            @XmlElement(name = "Emisor", required = true)
            protected Emisor emisor;
            @XmlElement(name = "Receptor", required = true)
            protected ReceptorRem receptor;
            @XmlElement(name = "Totales", required = true)
            protected CFEDefType.ERem.Encabezado.Totales totales;

            /**
             * Gets the value of the idDoc property.
             * 
             * @return
             *     possible object is
             *     {@link IdDocRem }
             *     
             */
            public IdDocRem getIdDoc() {
                return idDoc;
            }

            /**
             * Sets the value of the idDoc property.
             * 
             * @param value
             *     allowed object is
             *     {@link IdDocRem }
             *     
             */
            public void setIdDoc(IdDocRem value) {
                this.idDoc = value;
            }

            /**
             * Gets the value of the emisor property.
             * 
             * @return
             *     possible object is
             *     {@link Emisor }
             *     
             */
            public Emisor getEmisor() {
                return emisor;
            }

            /**
             * Sets the value of the emisor property.
             * 
             * @param value
             *     allowed object is
             *     {@link Emisor }
             *     
             */
            public void setEmisor(Emisor value) {
                this.emisor = value;
            }

            /**
             * Gets the value of the receptor property.
             * 
             * @return
             *     possible object is
             *     {@link ReceptorRem }
             *     
             */
            public ReceptorRem getReceptor() {
                return receptor;
            }

            /**
             * Sets the value of the receptor property.
             * 
             * @param value
             *     allowed object is
             *     {@link ReceptorRem }
             *     
             */
            public void setReceptor(ReceptorRem value) {
                this.receptor = value;
            }

            /**
             * Gets the value of the totales property.
             * 
             * @return
             *     possible object is
             *     {@link CFEDefType.ERem.Encabezado.Totales }
             *     
             */
            public CFEDefType.ERem.Encabezado.Totales getTotales() {
                return totales;
            }

            /**
             * Sets the value of the totales property.
             * 
             * @param value
             *     allowed object is
             *     {@link CFEDefType.ERem.Encabezado.Totales }
             *     
             */
            public void setTotales(CFEDefType.ERem.Encabezado.Totales value) {
                this.totales = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="CantLinDet">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://cfe.dgi.gub.uy}LineasDetType">
             *               &lt;totalDigits value="3"/>
             *               &lt;fractionDigits value="0"/>
             *               &lt;maxInclusive value="200"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "cantLinDet"
            })
            public static class Totales {

                @XmlElement(name = "CantLinDet")
                protected int cantLinDet;

                /**
                 * Gets the value of the cantLinDet property.
                 * 
                 */
                public int getCantLinDet() {
                    return cantLinDet;
                }

                /**
                 * Sets the value of the cantLinDet property.
                 * 
                 */
                public void setCantLinDet(int value) {
                    this.cantLinDet = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TmstFirma" type="{http://cfe.dgi.gub.uy}FechaHoraType"/>
     *         &lt;element name="Encabezado">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="IdDoc" type="{http://cfe.dgi.gub.uy}IdDoc_Resg"/>
     *                   &lt;element name="Emisor" type="{http://cfe.dgi.gub.uy}Emisor"/>
     *                   &lt;element name="Receptor" type="{http://cfe.dgi.gub.uy}Receptor_Resg"/>
     *                   &lt;element name="Totales" type="{http://cfe.dgi.gub.uy}Totales_Resg"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Detalle">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Item" type="{http://cfe.dgi.gub.uy}Item_Resg" maxOccurs="200"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="SubTotInfo" type="{http://cfe.dgi.gub.uy}SubTotInfo" minOccurs="0"/>
     *         &lt;element name="Referencia" type="{http://cfe.dgi.gub.uy}Referencia" minOccurs="0"/>
     *         &lt;element name="CAEData" type="{http://cfe.dgi.gub.uy}CAEDataType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tmstFirma",
        "encabezado",
        "detalle",
        "subTotInfo",
        "referencia",
        "caeData"
    })
    public static class EResg {

        @XmlElement(name = "TmstFirma", required = true)
        protected XMLGregorianCalendar tmstFirma;
        @XmlElement(name = "Encabezado", required = true)
        protected CFEDefType.EResg.Encabezado encabezado;
        @XmlElement(name = "Detalle", required = true)
        protected CFEDefType.EResg.Detalle detalle;
        @XmlElement(name = "SubTotInfo")
        protected SubTotInfo subTotInfo;
        @XmlElement(name = "Referencia")
        protected Referencia referencia;
        @XmlElement(name = "CAEData", required = true)
        protected CAEDataType caeData;

        /**
         * Gets the value of the tmstFirma property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTmstFirma() {
            return tmstFirma;
        }

        /**
         * Sets the value of the tmstFirma property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTmstFirma(XMLGregorianCalendar value) {
            this.tmstFirma = value;
        }

        /**
         * Gets the value of the encabezado property.
         * 
         * @return
         *     possible object is
         *     {@link CFEDefType.EResg.Encabezado }
         *     
         */
        public CFEDefType.EResg.Encabezado getEncabezado() {
            return encabezado;
        }

        /**
         * Sets the value of the encabezado property.
         * 
         * @param value
         *     allowed object is
         *     {@link CFEDefType.EResg.Encabezado }
         *     
         */
        public void setEncabezado(CFEDefType.EResg.Encabezado value) {
            this.encabezado = value;
        }

        /**
         * Gets the value of the detalle property.
         * 
         * @return
         *     possible object is
         *     {@link CFEDefType.EResg.Detalle }
         *     
         */
        public CFEDefType.EResg.Detalle getDetalle() {
            return detalle;
        }

        /**
         * Sets the value of the detalle property.
         * 
         * @param value
         *     allowed object is
         *     {@link CFEDefType.EResg.Detalle }
         *     
         */
        public void setDetalle(CFEDefType.EResg.Detalle value) {
            this.detalle = value;
        }

        /**
         * Gets the value of the subTotInfo property.
         * 
         * @return
         *     possible object is
         *     {@link SubTotInfo }
         *     
         */
        public SubTotInfo getSubTotInfo() {
            return subTotInfo;
        }

        /**
         * Sets the value of the subTotInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link SubTotInfo }
         *     
         */
        public void setSubTotInfo(SubTotInfo value) {
            this.subTotInfo = value;
        }

        /**
         * Gets the value of the referencia property.
         * 
         * @return
         *     possible object is
         *     {@link Referencia }
         *     
         */
        public Referencia getReferencia() {
            return referencia;
        }

        /**
         * Sets the value of the referencia property.
         * 
         * @param value
         *     allowed object is
         *     {@link Referencia }
         *     
         */
        public void setReferencia(Referencia value) {
            this.referencia = value;
        }

        /**
         * Gets the value of the caeData property.
         * 
         * @return
         *     possible object is
         *     {@link CAEDataType }
         *     
         */
        public CAEDataType getCAEData() {
            return caeData;
        }

        /**
         * Sets the value of the caeData property.
         * 
         * @param value
         *     allowed object is
         *     {@link CAEDataType }
         *     
         */
        public void setCAEData(CAEDataType value) {
            this.caeData = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Item" type="{http://cfe.dgi.gub.uy}Item_Resg" maxOccurs="200"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "item"
        })
        public static class Detalle {

            @XmlElement(name = "Item", required = true)
            protected List<ItemResg> item;

            /**
             * Gets the value of the item property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the item property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getItem().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ItemResg }
             * 
             * 
             */
            public List<ItemResg> getItem() {
                if (item == null) {
                    item = new ArrayList<ItemResg>();
                }
                return this.item;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="IdDoc" type="{http://cfe.dgi.gub.uy}IdDoc_Resg"/>
         *         &lt;element name="Emisor" type="{http://cfe.dgi.gub.uy}Emisor"/>
         *         &lt;element name="Receptor" type="{http://cfe.dgi.gub.uy}Receptor_Resg"/>
         *         &lt;element name="Totales" type="{http://cfe.dgi.gub.uy}Totales_Resg"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "idDoc",
            "emisor",
            "receptor",
            "totales"
        })
        public static class Encabezado {

            @XmlElement(name = "IdDoc", required = true)
            protected IdDocResg idDoc;
            @XmlElement(name = "Emisor", required = true)
            protected Emisor emisor;
            @XmlElement(name = "Receptor", required = true)
            protected ReceptorResg receptor;
            @XmlElement(name = "Totales", required = true)
            protected TotalesResg totales;

            /**
             * Gets the value of the idDoc property.
             * 
             * @return
             *     possible object is
             *     {@link IdDocResg }
             *     
             */
            public IdDocResg getIdDoc() {
                return idDoc;
            }

            /**
             * Sets the value of the idDoc property.
             * 
             * @param value
             *     allowed object is
             *     {@link IdDocResg }
             *     
             */
            public void setIdDoc(IdDocResg value) {
                this.idDoc = value;
            }

            /**
             * Gets the value of the emisor property.
             * 
             * @return
             *     possible object is
             *     {@link Emisor }
             *     
             */
            public Emisor getEmisor() {
                return emisor;
            }

            /**
             * Sets the value of the emisor property.
             * 
             * @param value
             *     allowed object is
             *     {@link Emisor }
             *     
             */
            public void setEmisor(Emisor value) {
                this.emisor = value;
            }

            /**
             * Gets the value of the receptor property.
             * 
             * @return
             *     possible object is
             *     {@link ReceptorResg }
             *     
             */
            public ReceptorResg getReceptor() {
                return receptor;
            }

            /**
             * Sets the value of the receptor property.
             * 
             * @param value
             *     allowed object is
             *     {@link ReceptorResg }
             *     
             */
            public void setReceptor(ReceptorResg value) {
                this.receptor = value;
            }

            /**
             * Gets the value of the totales property.
             * 
             * @return
             *     possible object is
             *     {@link TotalesResg }
             *     
             */
            public TotalesResg getTotales() {
                return totales;
            }

            /**
             * Sets the value of the totales property.
             * 
             * @param value
             *     allowed object is
             *     {@link TotalesResg }
             *     
             */
            public void setTotales(TotalesResg value) {
                this.totales = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TmstFirma" type="{http://cfe.dgi.gub.uy}FechaHoraType"/>
     *         &lt;element name="Encabezado">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="IdDoc" type="{http://cfe.dgi.gub.uy}IdDoc_Tck"/>
     *                   &lt;element name="Emisor" type="{http://cfe.dgi.gub.uy}Emisor"/>
     *                   &lt;element name="Receptor" type="{http://cfe.dgi.gub.uy}Receptor_Tck" minOccurs="0"/>
     *                   &lt;element name="Totales" type="{http://cfe.dgi.gub.uy}Totales"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Detalle">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Item" type="{http://cfe.dgi.gub.uy}Item_Det_Fact" maxOccurs="700"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="SubTotInfo" type="{http://cfe.dgi.gub.uy}SubTotInfo" minOccurs="0"/>
     *         &lt;element name="DscRcgGlobal" type="{http://cfe.dgi.gub.uy}DscRcgGlobal" minOccurs="0"/>
     *         &lt;element name="MediosPago" type="{http://cfe.dgi.gub.uy}MediosPago" minOccurs="0"/>
     *         &lt;element name="Referencia" type="{http://cfe.dgi.gub.uy}Referencia" minOccurs="0"/>
     *         &lt;element name="CAEData" type="{http://cfe.dgi.gub.uy}CAEDataType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tmstFirma",
        "encabezado",
        "detalle",
        "subTotInfo",
        "dscRcgGlobal",
        "mediosPago",
        "referencia",
        "caeData"
    })
    public static class ETck {

        @XmlElement(name = "TmstFirma", required = true)
        protected XMLGregorianCalendar tmstFirma;
        @XmlElement(name = "Encabezado", required = true)
        protected CFEDefType.ETck.Encabezado encabezado;
        @XmlElement(name = "Detalle", required = true)
        protected CFEDefType.ETck.Detalle detalle;
        @XmlElement(name = "SubTotInfo")
        protected SubTotInfo subTotInfo;
        @XmlElement(name = "DscRcgGlobal")
        protected DscRcgGlobal dscRcgGlobal;
        @XmlElement(name = "MediosPago")
        protected MediosPago mediosPago;
        @XmlElement(name = "Referencia")
        protected Referencia referencia;
        @XmlElement(name = "CAEData", required = true)
        protected CAEDataType caeData;

        /**
         * Gets the value of the tmstFirma property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTmstFirma() {
            return tmstFirma;
        }

        /**
         * Sets the value of the tmstFirma property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTmstFirma(XMLGregorianCalendar value) {
            this.tmstFirma = value;
        }

        /**
         * Gets the value of the encabezado property.
         * 
         * @return
         *     possible object is
         *     {@link CFEDefType.ETck.Encabezado }
         *     
         */
        public CFEDefType.ETck.Encabezado getEncabezado() {
            return encabezado;
        }

        /**
         * Sets the value of the encabezado property.
         * 
         * @param value
         *     allowed object is
         *     {@link CFEDefType.ETck.Encabezado }
         *     
         */
        public void setEncabezado(CFEDefType.ETck.Encabezado value) {
            this.encabezado = value;
        }

        /**
         * Gets the value of the detalle property.
         * 
         * @return
         *     possible object is
         *     {@link CFEDefType.ETck.Detalle }
         *     
         */
        public CFEDefType.ETck.Detalle getDetalle() {
            return detalle;
        }

        /**
         * Sets the value of the detalle property.
         * 
         * @param value
         *     allowed object is
         *     {@link CFEDefType.ETck.Detalle }
         *     
         */
        public void setDetalle(CFEDefType.ETck.Detalle value) {
            this.detalle = value;
        }

        /**
         * Gets the value of the subTotInfo property.
         * 
         * @return
         *     possible object is
         *     {@link SubTotInfo }
         *     
         */
        public SubTotInfo getSubTotInfo() {
            return subTotInfo;
        }

        /**
         * Sets the value of the subTotInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link SubTotInfo }
         *     
         */
        public void setSubTotInfo(SubTotInfo value) {
            this.subTotInfo = value;
        }

        /**
         * Gets the value of the dscRcgGlobal property.
         * 
         * @return
         *     possible object is
         *     {@link DscRcgGlobal }
         *     
         */
        public DscRcgGlobal getDscRcgGlobal() {
            return dscRcgGlobal;
        }

        /**
         * Sets the value of the dscRcgGlobal property.
         * 
         * @param value
         *     allowed object is
         *     {@link DscRcgGlobal }
         *     
         */
        public void setDscRcgGlobal(DscRcgGlobal value) {
            this.dscRcgGlobal = value;
        }

        /**
         * Gets the value of the mediosPago property.
         * 
         * @return
         *     possible object is
         *     {@link MediosPago }
         *     
         */
        public MediosPago getMediosPago() {
            return mediosPago;
        }

        /**
         * Sets the value of the mediosPago property.
         * 
         * @param value
         *     allowed object is
         *     {@link MediosPago }
         *     
         */
        public void setMediosPago(MediosPago value) {
            this.mediosPago = value;
        }

        /**
         * Gets the value of the referencia property.
         * 
         * @return
         *     possible object is
         *     {@link Referencia }
         *     
         */
        public Referencia getReferencia() {
            return referencia;
        }

        /**
         * Sets the value of the referencia property.
         * 
         * @param value
         *     allowed object is
         *     {@link Referencia }
         *     
         */
        public void setReferencia(Referencia value) {
            this.referencia = value;
        }

        /**
         * Gets the value of the caeData property.
         * 
         * @return
         *     possible object is
         *     {@link CAEDataType }
         *     
         */
        public CAEDataType getCAEData() {
            return caeData;
        }

        /**
         * Sets the value of the caeData property.
         * 
         * @param value
         *     allowed object is
         *     {@link CAEDataType }
         *     
         */
        public void setCAEData(CAEDataType value) {
            this.caeData = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Item" type="{http://cfe.dgi.gub.uy}Item_Det_Fact" maxOccurs="700"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "item"
        })
        public static class Detalle {

            @XmlElement(name = "Item", required = true)
            protected List<ItemDetFact> item;

            /**
             * Gets the value of the item property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the item property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getItem().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ItemDetFact }
             * 
             * 
             */
            public List<ItemDetFact> getItem() {
                if (item == null) {
                    item = new ArrayList<ItemDetFact>();
                }
                return this.item;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="IdDoc" type="{http://cfe.dgi.gub.uy}IdDoc_Tck"/>
         *         &lt;element name="Emisor" type="{http://cfe.dgi.gub.uy}Emisor"/>
         *         &lt;element name="Receptor" type="{http://cfe.dgi.gub.uy}Receptor_Tck" minOccurs="0"/>
         *         &lt;element name="Totales" type="{http://cfe.dgi.gub.uy}Totales"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "idDoc",
            "emisor",
            "receptor",
            "totales"
        })
        public static class Encabezado {

            @XmlElement(name = "IdDoc", required = true)
            protected IdDocTck idDoc;
            @XmlElement(name = "Emisor", required = true)
            protected Emisor emisor;
            @XmlElement(name = "Receptor")
            protected ReceptorTck receptor;
            @XmlElement(name = "Totales", required = true)
            protected uy.gub.dgi.cfe.Totales totales;

            /**
             * Gets the value of the idDoc property.
             * 
             * @return
             *     possible object is
             *     {@link IdDocTck }
             *     
             */
            public IdDocTck getIdDoc() {
                return idDoc;
            }

            /**
             * Sets the value of the idDoc property.
             * 
             * @param value
             *     allowed object is
             *     {@link IdDocTck }
             *     
             */
            public void setIdDoc(IdDocTck value) {
                this.idDoc = value;
            }

            /**
             * Gets the value of the emisor property.
             * 
             * @return
             *     possible object is
             *     {@link Emisor }
             *     
             */
            public Emisor getEmisor() {
                return emisor;
            }

            /**
             * Sets the value of the emisor property.
             * 
             * @param value
             *     allowed object is
             *     {@link Emisor }
             *     
             */
            public void setEmisor(Emisor value) {
                this.emisor = value;
            }

            /**
             * Gets the value of the receptor property.
             * 
             * @return
             *     possible object is
             *     {@link ReceptorTck }
             *     
             */
            public ReceptorTck getReceptor() {
                return receptor;
            }

            /**
             * Sets the value of the receptor property.
             * 
             * @param value
             *     allowed object is
             *     {@link ReceptorTck }
             *     
             */
            public void setReceptor(ReceptorTck value) {
                this.receptor = value;
            }

            /**
             * Gets the value of the totales property.
             * 
             * @return
             *     possible object is
             *     {@link uy.gub.dgi.cfe.Totales }
             *     
             */
            public uy.gub.dgi.cfe.Totales getTotales() {
                return totales;
            }

            /**
             * Sets the value of the totales property.
             * 
             * @param value
             *     allowed object is
             *     {@link uy.gub.dgi.cfe.Totales }
             *     
             */
            public void setTotales(uy.gub.dgi.cfe.Totales value) {
                this.totales = value;
            }

        }

    }


	public EFactX getEFactX() {
		// TODO Auto-generated method stub
		return null;
	}

}
