//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.29 at 03:49:49 PM UYST 
//


package uy.gub.dgi.cfe;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Comprobante Fiscal Electronico
 * 
 * <p>Java class for CFEDefType_X complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CFEDefType_X">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="eTck">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="Encabezado">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="IdDoc">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;element name="TipoCFE">
 *                                           &lt;simpleType>
 *                                             &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
 *                                               &lt;enumeration value="101"/>
 *                                               &lt;enumeration value="102"/>
 *                                               &lt;enumeration value="103"/>
 *                                               &lt;enumeration value="201"/>
 *                                               &lt;enumeration value="202"/>
 *                                               &lt;enumeration value="203"/>
 *                                             &lt;/restriction>
 *                                           &lt;/simpleType>
 *                                         &lt;/element>
 *                                         &lt;element name="Serie" type="{http://cfe.dgi.gub.uy}SerieType"/>
 *                                         &lt;element name="Nro" type="{http://cfe.dgi.gub.uy}NroCFEType"/>
 *                                         &lt;element name="FchEmis" type="{http://cfe.dgi.gub.uy}FechaType"/>
 *                                         &lt;element name="PeriodoDesde" type="{http://cfe.dgi.gub.uy}FechaType" minOccurs="0"/>
 *                                         &lt;element name="PeridoHasta" type="{http://cfe.dgi.gub.uy}FechaType" minOccurs="0"/>
 *                                         &lt;element name="MntBruto" minOccurs="0">
 *                                           &lt;simpleType>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                                               &lt;enumeration value="1"/>
 *                                             &lt;/restriction>
 *                                           &lt;/simpleType>
 *                                         &lt;/element>
 *                                         &lt;element name="FmaPago">
 *                                           &lt;simpleType>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *                                               &lt;enumeration value="1"/>
 *                                               &lt;enumeration value="2"/>
 *                                             &lt;/restriction>
 *                                           &lt;/simpleType>
 *                                         &lt;/element>
 *                                         &lt;element name="FchVenc" type="{http://cfe.dgi.gub.uy}FechaType" minOccurs="0"/>
 *                                       &lt;/sequence>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                               &lt;element name="Emisor" type="{http://cfe.dgi.gub.uy}Emisor"/>
 *                               &lt;element name="Receptor" type="{http://cfe.dgi.gub.uy}Receptor_Tck" minOccurs="0"/>
 *                               &lt;element name="Totales" type="{http://cfe.dgi.gub.uy}Totales"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="Detalle">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="Item" type="{http://cfe.dgi.gub.uy}Item_Det_Fact" maxOccurs="700"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="SubTotInfo" type="{http://cfe.dgi.gub.uy}SubTotInfo" minOccurs="0"/>
 *                     &lt;element name="DscRcgGlobal" type="{http://cfe.dgi.gub.uy}DscRcgGlobal" minOccurs="0"/>
 *                     &lt;element name="MediosPago" type="{http://cfe.dgi.gub.uy}MediosPago" minOccurs="0"/>
 *                     &lt;element name="Referencia" type="{http://cfe.dgi.gub.uy}ReferenciaEl" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="eFact_X">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="Encabezado">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="IdDoc" type="{http://cfe.dgi.gub.uy}IdDoc_Fact"/>
 *                               &lt;element name="Emisor" type="{http://cfe.dgi.gub.uy}Emisor"/>
 *                               &lt;element name="Receptor" type="{http://cfe.dgi.gub.uy}Receptor_Fact"/>
 *                               &lt;element name="Totales" type="{http://cfe.dgi.gub.uy}Totales"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="Detalle">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="Item" type="{http://cfe.dgi.gub.uy}Item_Det_Fact" maxOccurs="200"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="SubTotInfo" type="{http://cfe.dgi.gub.uy}SubTotInfo" minOccurs="0"/>
 *                     &lt;element name="DscRcgGlobal" type="{http://cfe.dgi.gub.uy}DscRcgGlobal" minOccurs="0"/>
 *                     &lt;element name="MediosPago" type="{http://cfe.dgi.gub.uy}MediosPago" minOccurs="0"/>
 *                     &lt;element name="ReferenciaEl" type="{http://cfe.dgi.gub.uy}ReferenciaEl" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="eRem_X">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="Encabezado">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="IdDoc" type="{http://cfe.dgi.gub.uy}IdDoc_Rem"/>
 *                               &lt;element name="Emisor" type="{http://cfe.dgi.gub.uy}Emisor"/>
 *                               &lt;element name="Receptor" type="{http://cfe.dgi.gub.uy}Receptor_Rem"/>
 *                               &lt;element name="Totales">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;element name="CantLinDet">
 *                                           &lt;simpleType>
 *                                             &lt;restriction base="{http://cfe.dgi.gub.uy}LineasDetType">
 *                                               &lt;totalDigits value="3"/>
 *                                               &lt;fractionDigits value="0"/>
 *                                               &lt;maxInclusive value="200"/>
 *                                             &lt;/restriction>
 *                                           &lt;/simpleType>
 *                                         &lt;/element>
 *                                       &lt;/sequence>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="Detalle">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="Item" type="{http://cfe.dgi.gub.uy}Item_Rem" maxOccurs="200"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="SubTotInfo" type="{http://cfe.dgi.gub.uy}SubTotInfo" minOccurs="0"/>
 *                     &lt;element name="ReferenciaEl" type="{http://cfe.dgi.gub.uy}ReferenciaEl" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="eResg_X">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="Encabezado">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="IdDoc" type="{http://cfe.dgi.gub.uy}IdDoc_Resg"/>
 *                               &lt;element name="Emisor" type="{http://cfe.dgi.gub.uy}Emisor"/>
 *                               &lt;element name="Receptor" type="{http://cfe.dgi.gub.uy}Receptor_Resg"/>
 *                               &lt;element name="Totales" type="{http://cfe.dgi.gub.uy}Totales_Resg"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="Detalle">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="Item" type="{http://cfe.dgi.gub.uy}Item_Resg" maxOccurs="200"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="SubTotInfo" type="{http://cfe.dgi.gub.uy}SubTotInfo" minOccurs="0"/>
 *                     &lt;element name="ReferenciaEl" type="{http://cfe.dgi.gub.uy}ReferenciaEl" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="tipoCFE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" fixed="1.0">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="3"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="Factura")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CFEDefType_X", propOrder = {
    "eTck",
    "eFactX",
    "eRemX",
    "eResgX",
    "tipoCFE"
})
public class CFEDefTypeX {

    protected CFEDefTypeX.ETck eTck;
    @XmlElement(name = "eFact_X")
    protected CFEDefTypeX.EFactX eFactX;
    @XmlElement(name = "eRem_X")
    protected CFEDefTypeX.ERemX eRemX;
    @XmlElement(name = "eResg_X")
    protected CFEDefTypeX.EResgX eResgX;
    protected int tipoCFE;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the eTck property.
     * 
     * @return
     *     possible object is
     *     {@link CFEDefTypeX.ETck }
     *     
     */
    public CFEDefTypeX.ETck getETck() {
        return eTck;
    }

    /**
     * Sets the value of the eTck property.
     * 
     * @param value
     *     allowed object is
     *     {@link CFEDefTypeX.ETck }
     *     
     */
    public void setETck(CFEDefTypeX.ETck value) {
        this.eTck = value;
    }

    /**
     * Gets the value of the eFactX property.
     * 
     * @return
     *     possible object is
     *     {@link CFEDefTypeX.EFactX }
     *     
     */
    public CFEDefTypeX.EFactX getEFactX() {
        return eFactX;
    }

    /**
     * Sets the value of the eFactX property.
     * 
     * @param value
     *     allowed object is
     *     {@link CFEDefTypeX.EFactX }
     *     
     */
    public void setEFactX(CFEDefTypeX.EFactX value) {
        this.eFactX = value;
    }

    /**
     * Gets the value of the eRemX property.
     * 
     * @return
     *     possible object is
     *     {@link CFEDefTypeX.ERemX }
     *     
     */
    public CFEDefTypeX.ERemX getERemX() {
        return eRemX;
    }

    /**
     * Sets the value of the eRemX property.
     * 
     * @param value
     *     allowed object is
     *     {@link CFEDefTypeX.ERemX }
     *     
     */
    public void setERemX(CFEDefTypeX.ERemX value) {
        this.eRemX = value;
    }

    /**
     * Gets the value of the eResgX property.
     * 
     * @return
     *     possible object is
     *     {@link CFEDefTypeX.EResgX }
     *     
     */
    public CFEDefTypeX.EResgX getEResgX() {
        return eResgX;
    }

    /**
     * Sets the value of the eResgX property.
     * 
     * @param value
     *     allowed object is
     *     {@link CFEDefTypeX.EResgX }
     *     
     */
    public void setEResgX(CFEDefTypeX.EResgX value) {
        this.eResgX = value;
    }

    /**
     * Gets the value of the tipoCFE property.
     * 
     */
    public int getTipoCFE() {
        return tipoCFE;
    }

    /**
     * Sets the value of the tipoCFE property.
     * 
     */
    public void setTipoCFE(int value) {
        this.tipoCFE = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Encabezado">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="IdDoc" type="{http://cfe.dgi.gub.uy}IdDoc_Fact"/>
     *                   &lt;element name="Emisor" type="{http://cfe.dgi.gub.uy}Emisor"/>
     *                   &lt;element name="Receptor" type="{http://cfe.dgi.gub.uy}Receptor_Fact"/>
     *                   &lt;element name="Totales" type="{http://cfe.dgi.gub.uy}Totales"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Detalle">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Item" type="{http://cfe.dgi.gub.uy}Item_Det_Fact" maxOccurs="200"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="SubTotInfo" type="{http://cfe.dgi.gub.uy}SubTotInfo" minOccurs="0"/>
     *         &lt;element name="DscRcgGlobal" type="{http://cfe.dgi.gub.uy}DscRcgGlobal" minOccurs="0"/>
     *         &lt;element name="MediosPago" type="{http://cfe.dgi.gub.uy}MediosPago" minOccurs="0"/>
     *         &lt;element name="ReferenciaEl" type="{http://cfe.dgi.gub.uy}ReferenciaEl" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "encabezado",
        "detalle",
        "subTotInfo",
        "dscRcgGlobal",
        "mediosPago",
        "referenciaEl"
    })
    public static class EFactX {

        @XmlElement(name = "Encabezado", required = true)
        protected CFEDefTypeX.EFactX.Encabezado encabezado;
        @XmlElement(name = "Detalle", required = true)
        protected CFEDefTypeX.EFactX.Detalle detalle;
        @XmlElement(name = "SubTotInfo")
        protected SubTotInfo subTotInfo;
        @XmlElement(name = "DscRcgGlobal")
        protected DscRcgGlobal dscRcgGlobal;
        @XmlElement(name = "MediosPago")
        protected MediosPago mediosPago;
        @XmlElement(name = "ReferenciaEl")
        protected ReferenciaEl referenciaEl;

        /**
         * Gets the value of the encabezado property.
         * 
         * @return
         *     possible object is
         *     {@link CFEDefTypeX.EFactX.Encabezado }
         *     
         */
        public CFEDefTypeX.EFactX.Encabezado getEncabezado() {
            return encabezado;
        }

        /**
         * Sets the value of the encabezado property.
         * 
         * @param value
         *     allowed object is
         *     {@link CFEDefTypeX.EFactX.Encabezado }
         *     
         */
        public void setEncabezado(CFEDefTypeX.EFactX.Encabezado value) {
            this.encabezado = value;
        }

        /**
         * Gets the value of the detalle property.
         * 
         * @return
         *     possible object is
         *     {@link CFEDefTypeX.EFactX.Detalle }
         *     
         */
        public CFEDefTypeX.EFactX.Detalle getDetalle() {
            return detalle;
        }

        /**
         * Sets the value of the detalle property.
         * 
         * @param value
         *     allowed object is
         *     {@link CFEDefTypeX.EFactX.Detalle }
         *     
         */
        public void setDetalle(CFEDefTypeX.EFactX.Detalle value) {
            this.detalle = value;
        }

        /**
         * Gets the value of the subTotInfo property.
         * 
         * @return
         *     possible object is
         *     {@link SubTotInfo }
         *     
         */
        public SubTotInfo getSubTotInfo() {
            return subTotInfo;
        }

        /**
         * Sets the value of the subTotInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link SubTotInfo }
         *     
         */
        public void setSubTotInfo(SubTotInfo value) {
            this.subTotInfo = value;
        }

        /**
         * Gets the value of the dscRcgGlobal property.
         * 
         * @return
         *     possible object is
         *     {@link DscRcgGlobal }
         *     
         */
        public DscRcgGlobal getDscRcgGlobal() {
            return dscRcgGlobal;
        }

        /**
         * Sets the value of the dscRcgGlobal property.
         * 
         * @param value
         *     allowed object is
         *     {@link DscRcgGlobal }
         *     
         */
        public void setDscRcgGlobal(DscRcgGlobal value) {
            this.dscRcgGlobal = value;
        }

        /**
         * Gets the value of the mediosPago property.
         * 
         * @return
         *     possible object is
         *     {@link MediosPago }
         *     
         */
        public MediosPago getMediosPago() {
            return mediosPago;
        }

        /**
         * Sets the value of the mediosPago property.
         * 
         * @param value
         *     allowed object is
         *     {@link MediosPago }
         *     
         */
        public void setMediosPago(MediosPago value) {
            this.mediosPago = value;
        }

        /**
         * Gets the value of the referenciaEl property.
         * 
         * @return
         *     possible object is
         *     {@link ReferenciaEl }
         *     
         */
        public ReferenciaEl getReferenciaEl() {
            return referenciaEl;
        }

        /**
         * Sets the value of the referenciaEl property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReferenciaEl }
         *     
         */
        public void setReferenciaEl(ReferenciaEl value) {
            this.referenciaEl = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Item" type="{http://cfe.dgi.gub.uy}Item_Det_Fact" maxOccurs="200"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "item"
        })
        public static class Detalle {

            @XmlElement(name = "Item", required = true)
            protected List<ItemDetFact> item;

            /**
             * Gets the value of the item property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the item property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getItem().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ItemDetFact }
             * 
             * 
             */
            public List<ItemDetFact> getItem() {
                if (item == null) {
                    item = new ArrayList<ItemDetFact>();
                }
                return this.item;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="IdDoc" type="{http://cfe.dgi.gub.uy}IdDoc_Fact"/>
         *         &lt;element name="Emisor" type="{http://cfe.dgi.gub.uy}Emisor"/>
         *         &lt;element name="Receptor" type="{http://cfe.dgi.gub.uy}Receptor_Fact"/>
         *         &lt;element name="Totales" type="{http://cfe.dgi.gub.uy}Totales"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "idDoc",
            "emisor",
            "receptor",
            "totales"
        })
        public static class Encabezado {

            @XmlElement(name = "IdDoc", required = true)
            protected IdDocFact idDoc;
            @XmlElement(name = "Emisor", required = true)
            protected Emisor emisor;
            @XmlElement(name = "Receptor", required = true)
            protected ReceptorFact receptor;
            @XmlElement(name = "Totales", required = true)
            protected uy.gub.dgi.cfe.Totales totales;

            /**
             * Gets the value of the idDoc property.
             * 
             * @return
             *     possible object is
             *     {@link IdDocFact }
             *     
             */
            public IdDocFact getIdDoc() {
                return idDoc;
            }

            /**
             * Sets the value of the idDoc property.
             * 
             * @param value
             *     allowed object is
             *     {@link IdDocFact }
             *     
             */
            public void setIdDoc(IdDocFact value) {
                this.idDoc = value;
            }

            /**
             * Gets the value of the emisor property.
             * 
             * @return
             *     possible object is
             *     {@link Emisor }
             *     
             */
            public Emisor getEmisor() {
                return emisor;
            }

            /**
             * Sets the value of the emisor property.
             * 
             * @param value
             *     allowed object is
             *     {@link Emisor }
             *     
             */
            public void setEmisor(Emisor value) {
                this.emisor = value;
            }

            /**
             * Gets the value of the receptor property.
             * 
             * @return
             *     possible object is
             *     {@link ReceptorFact }
             *     
             */
            public ReceptorFact getReceptor() {
                return receptor;
            }

            /**
             * Sets the value of the receptor property.
             * 
             * @param value
             *     allowed object is
             *     {@link ReceptorFact }
             *     
             */
            public void setReceptor(ReceptorFact value) {
                this.receptor = value;
            }

            /**
             * Gets the value of the totales property.
             * 
             * @return
             *     possible object is
             *     {@link uy.gub.dgi.cfe.Totales }
             *     
             */
            public uy.gub.dgi.cfe.Totales getTotales() {
                return totales;
            }

            /**
             * Sets the value of the totales property.
             * 
             * @param value
             *     allowed object is
             *     {@link uy.gub.dgi.cfe.Totales }
             *     
             */
            public void setTotales(uy.gub.dgi.cfe.Totales value) {
                this.totales = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Encabezado">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="IdDoc" type="{http://cfe.dgi.gub.uy}IdDoc_Rem"/>
     *                   &lt;element name="Emisor" type="{http://cfe.dgi.gub.uy}Emisor"/>
     *                   &lt;element name="Receptor" type="{http://cfe.dgi.gub.uy}Receptor_Rem"/>
     *                   &lt;element name="Totales">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="CantLinDet">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://cfe.dgi.gub.uy}LineasDetType">
     *                                   &lt;totalDigits value="3"/>
     *                                   &lt;fractionDigits value="0"/>
     *                                   &lt;maxInclusive value="200"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Detalle">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Item" type="{http://cfe.dgi.gub.uy}Item_Rem" maxOccurs="200"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="SubTotInfo" type="{http://cfe.dgi.gub.uy}SubTotInfo" minOccurs="0"/>
     *         &lt;element name="ReferenciaEl" type="{http://cfe.dgi.gub.uy}ReferenciaEl" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "encabezado",
        "detalle",
        "subTotInfo",
        "referenciaEl"
    })
    public static class ERemX {

        @XmlElement(name = "Encabezado", required = true)
        protected CFEDefTypeX.ERemX.Encabezado encabezado;
        @XmlElement(name = "Detalle", required = true)
        protected CFEDefTypeX.ERemX.Detalle detalle;
        @XmlElement(name = "SubTotInfo")
        protected SubTotInfo subTotInfo;
        @XmlElement(name = "ReferenciaEl")
        protected ReferenciaEl referenciaEl;

        /**
         * Gets the value of the encabezado property.
         * 
         * @return
         *     possible object is
         *     {@link CFEDefTypeX.ERemX.Encabezado }
         *     
         */
        public CFEDefTypeX.ERemX.Encabezado getEncabezado() {
            return encabezado;
        }

        /**
         * Sets the value of the encabezado property.
         * 
         * @param value
         *     allowed object is
         *     {@link CFEDefTypeX.ERemX.Encabezado }
         *     
         */
        public void setEncabezado(CFEDefTypeX.ERemX.Encabezado value) {
            this.encabezado = value;
        }

        /**
         * Gets the value of the detalle property.
         * 
         * @return
         *     possible object is
         *     {@link CFEDefTypeX.ERemX.Detalle }
         *     
         */
        public CFEDefTypeX.ERemX.Detalle getDetalle() {
            return detalle;
        }

        /**
         * Sets the value of the detalle property.
         * 
         * @param value
         *     allowed object is
         *     {@link CFEDefTypeX.ERemX.Detalle }
         *     
         */
        public void setDetalle(CFEDefTypeX.ERemX.Detalle value) {
            this.detalle = value;
        }

        /**
         * Gets the value of the subTotInfo property.
         * 
         * @return
         *     possible object is
         *     {@link SubTotInfo }
         *     
         */
        public SubTotInfo getSubTotInfo() {
            return subTotInfo;
        }

        /**
         * Sets the value of the subTotInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link SubTotInfo }
         *     
         */
        public void setSubTotInfo(SubTotInfo value) {
            this.subTotInfo = value;
        }

        /**
         * Gets the value of the referenciaEl property.
         * 
         * @return
         *     possible object is
         *     {@link ReferenciaEl }
         *     
         */
        public ReferenciaEl getReferenciaEl() {
            return referenciaEl;
        }

        /**
         * Sets the value of the referenciaEl property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReferenciaEl }
         *     
         */
        public void setReferenciaEl(ReferenciaEl value) {
            this.referenciaEl = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Item" type="{http://cfe.dgi.gub.uy}Item_Rem" maxOccurs="200"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "item"
        })
        public static class Detalle {

            @XmlElement(name = "Item", required = true)
            protected List<ItemRem> item;

            /**
             * Gets the value of the item property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the item property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getItem().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ItemRem }
             * 
             * 
             */
            public List<ItemRem> getItem() {
                if (item == null) {
                    item = new ArrayList<ItemRem>();
                }
                return this.item;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="IdDoc" type="{http://cfe.dgi.gub.uy}IdDoc_Rem"/>
         *         &lt;element name="Emisor" type="{http://cfe.dgi.gub.uy}Emisor"/>
         *         &lt;element name="Receptor" type="{http://cfe.dgi.gub.uy}Receptor_Rem"/>
         *         &lt;element name="Totales">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="CantLinDet">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://cfe.dgi.gub.uy}LineasDetType">
         *                         &lt;totalDigits value="3"/>
         *                         &lt;fractionDigits value="0"/>
         *                         &lt;maxInclusive value="200"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "idDoc",
            "emisor",
            "receptor",
            "totales"
        })
        public static class Encabezado {

            @XmlElement(name = "IdDoc", required = true)
            protected IdDocRem idDoc;
            @XmlElement(name = "Emisor", required = true)
            protected Emisor emisor;
            @XmlElement(name = "Receptor", required = true)
            protected ReceptorRem receptor;
            @XmlElement(name = "Totales", required = true)
            protected CFEDefTypeX.ERemX.Encabezado.Totales totales;

            /**
             * Gets the value of the idDoc property.
             * 
             * @return
             *     possible object is
             *     {@link IdDocRem }
             *     
             */
            public IdDocRem getIdDoc() {
                return idDoc;
            }

            /**
             * Sets the value of the idDoc property.
             * 
             * @param value
             *     allowed object is
             *     {@link IdDocRem }
             *     
             */
            public void setIdDoc(IdDocRem value) {
                this.idDoc = value;
            }

            /**
             * Gets the value of the emisor property.
             * 
             * @return
             *     possible object is
             *     {@link Emisor }
             *     
             */
            public Emisor getEmisor() {
                return emisor;
            }

            /**
             * Sets the value of the emisor property.
             * 
             * @param value
             *     allowed object is
             *     {@link Emisor }
             *     
             */
            public void setEmisor(Emisor value) {
                this.emisor = value;
            }

            /**
             * Gets the value of the receptor property.
             * 
             * @return
             *     possible object is
             *     {@link ReceptorRem }
             *     
             */
            public ReceptorRem getReceptor() {
                return receptor;
            }

            /**
             * Sets the value of the receptor property.
             * 
             * @param value
             *     allowed object is
             *     {@link ReceptorRem }
             *     
             */
            public void setReceptor(ReceptorRem value) {
                this.receptor = value;
            }

            /**
             * Gets the value of the totales property.
             * 
             * @return
             *     possible object is
             *     {@link CFEDefTypeX.ERemX.Encabezado.Totales }
             *     
             */
            public CFEDefTypeX.ERemX.Encabezado.Totales getTotales() {
                return totales;
            }

            /**
             * Sets the value of the totales property.
             * 
             * @param value
             *     allowed object is
             *     {@link CFEDefTypeX.ERemX.Encabezado.Totales }
             *     
             */
            public void setTotales(CFEDefTypeX.ERemX.Encabezado.Totales value) {
                this.totales = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="CantLinDet">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://cfe.dgi.gub.uy}LineasDetType">
             *               &lt;totalDigits value="3"/>
             *               &lt;fractionDigits value="0"/>
             *               &lt;maxInclusive value="200"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "cantLinDet"
            })
            public static class Totales {

                @XmlElement(name = "CantLinDet")
                protected int cantLinDet;

                /**
                 * Gets the value of the cantLinDet property.
                 * 
                 */
                public int getCantLinDet() {
                    return cantLinDet;
                }

                /**
                 * Sets the value of the cantLinDet property.
                 * 
                 */
                public void setCantLinDet(int value) {
                    this.cantLinDet = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Encabezado">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="IdDoc" type="{http://cfe.dgi.gub.uy}IdDoc_Resg"/>
     *                   &lt;element name="Emisor" type="{http://cfe.dgi.gub.uy}Emisor"/>
     *                   &lt;element name="Receptor" type="{http://cfe.dgi.gub.uy}Receptor_Resg"/>
     *                   &lt;element name="Totales" type="{http://cfe.dgi.gub.uy}Totales_Resg"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Detalle">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Item" type="{http://cfe.dgi.gub.uy}Item_Resg" maxOccurs="200"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="SubTotInfo" type="{http://cfe.dgi.gub.uy}SubTotInfo" minOccurs="0"/>
     *         &lt;element name="ReferenciaEl" type="{http://cfe.dgi.gub.uy}ReferenciaEl" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "encabezado",
        "detalle",
        "subTotInfo",
        "referenciaEl"
    })
    public static class EResgX {

        @XmlElement(name = "Encabezado", required = true)
        protected CFEDefTypeX.EResgX.Encabezado encabezado;
        @XmlElement(name = "Detalle", required = true)
        protected CFEDefTypeX.EResgX.Detalle detalle;
        @XmlElement(name = "SubTotInfo")
        protected SubTotInfo subTotInfo;
        @XmlElement(name = "ReferenciaEl")
        protected ReferenciaEl referenciaEl;

        /**
         * Gets the value of the encabezado property.
         * 
         * @return
         *     possible object is
         *     {@link CFEDefTypeX.EResgX.Encabezado }
         *     
         */
        public CFEDefTypeX.EResgX.Encabezado getEncabezado() {
            return encabezado;
        }

        /**
         * Sets the value of the encabezado property.
         * 
         * @param value
         *     allowed object is
         *     {@link CFEDefTypeX.EResgX.Encabezado }
         *     
         */
        public void setEncabezado(CFEDefTypeX.EResgX.Encabezado value) {
            this.encabezado = value;
        }

        /**
         * Gets the value of the detalle property.
         * 
         * @return
         *     possible object is
         *     {@link CFEDefTypeX.EResgX.Detalle }
         *     
         */
        public CFEDefTypeX.EResgX.Detalle getDetalle() {
            return detalle;
        }

        /**
         * Sets the value of the detalle property.
         * 
         * @param value
         *     allowed object is
         *     {@link CFEDefTypeX.EResgX.Detalle }
         *     
         */
        public void setDetalle(CFEDefTypeX.EResgX.Detalle value) {
            this.detalle = value;
        }

        /**
         * Gets the value of the subTotInfo property.
         * 
         * @return
         *     possible object is
         *     {@link SubTotInfo }
         *     
         */
        public SubTotInfo getSubTotInfo() {
            return subTotInfo;
        }

        /**
         * Sets the value of the subTotInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link SubTotInfo }
         *     
         */
        public void setSubTotInfo(SubTotInfo value) {
            this.subTotInfo = value;
        }

        /**
         * Gets the value of the referenciaEl property.
         * 
         * @return
         *     possible object is
         *     {@link ReferenciaEl }
         *     
         */
        public ReferenciaEl getReferenciaEl() {
            return referenciaEl;
        }

        /**
         * Sets the value of the referenciaEl property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReferenciaEl }
         *     
         */
        public void setReferenciaEl(ReferenciaEl value) {
            this.referenciaEl = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Item" type="{http://cfe.dgi.gub.uy}Item_Resg" maxOccurs="200"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "item"
        })
        public static class Detalle {

            @XmlElement(name = "Item", required = true)
            protected List<ItemResg> item;

            /**
             * Gets the value of the item property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the item property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getItem().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ItemResg }
             * 
             * 
             */
            public List<ItemResg> getItem() {
                if (item == null) {
                    item = new ArrayList<ItemResg>();
                }
                return this.item;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="IdDoc" type="{http://cfe.dgi.gub.uy}IdDoc_Resg"/>
         *         &lt;element name="Emisor" type="{http://cfe.dgi.gub.uy}Emisor"/>
         *         &lt;element name="Receptor" type="{http://cfe.dgi.gub.uy}Receptor_Resg"/>
         *         &lt;element name="Totales" type="{http://cfe.dgi.gub.uy}Totales_Resg"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "idDoc",
            "emisor",
            "receptor",
            "totales"
        })
        public static class Encabezado {

            @XmlElement(name = "IdDoc", required = true)
            protected IdDocResg idDoc;
            @XmlElement(name = "Emisor", required = true)
            protected Emisor emisor;
            @XmlElement(name = "Receptor", required = true)
            protected ReceptorResg receptor;
            @XmlElement(name = "Totales", required = true)
            protected TotalesResg totales;

            /**
             * Gets the value of the idDoc property.
             * 
             * @return
             *     possible object is
             *     {@link IdDocResg }
             *     
             */
            public IdDocResg getIdDoc() {
                return idDoc;
            }

            /**
             * Sets the value of the idDoc property.
             * 
             * @param value
             *     allowed object is
             *     {@link IdDocResg }
             *     
             */
            public void setIdDoc(IdDocResg value) {
                this.idDoc = value;
            }

            /**
             * Gets the value of the emisor property.
             * 
             * @return
             *     possible object is
             *     {@link Emisor }
             *     
             */
            public Emisor getEmisor() {
                return emisor;
            }

            /**
             * Sets the value of the emisor property.
             * 
             * @param value
             *     allowed object is
             *     {@link Emisor }
             *     
             */
            public void setEmisor(Emisor value) {
                this.emisor = value;
            }

            /**
             * Gets the value of the receptor property.
             * 
             * @return
             *     possible object is
             *     {@link ReceptorResg }
             *     
             */
            public ReceptorResg getReceptor() {
                return receptor;
            }

            /**
             * Sets the value of the receptor property.
             * 
             * @param value
             *     allowed object is
             *     {@link ReceptorResg }
             *     
             */
            public void setReceptor(ReceptorResg value) {
                this.receptor = value;
            }

            /**
             * Gets the value of the totales property.
             * 
             * @return
             *     possible object is
             *     {@link TotalesResg }
             *     
             */
            public TotalesResg getTotales() {
                return totales;
            }

            /**
             * Sets the value of the totales property.
             * 
             * @param value
             *     allowed object is
             *     {@link TotalesResg }
             *     
             */
            public void setTotales(TotalesResg value) {
                this.totales = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Encabezado">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="IdDoc">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="TipoCFE">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
     *                                   &lt;enumeration value="101"/>
     *                                   &lt;enumeration value="102"/>
     *                                   &lt;enumeration value="103"/>
     *                                   &lt;enumeration value="201"/>
     *                                   &lt;enumeration value="202"/>
     *                                   &lt;enumeration value="203"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="Serie" type="{http://cfe.dgi.gub.uy}SerieType"/>
     *                             &lt;element name="Nro" type="{http://cfe.dgi.gub.uy}NroCFEType"/>
     *                             &lt;element name="FchEmis" type="{http://cfe.dgi.gub.uy}FechaType"/>
     *                             &lt;element name="PeriodoDesde" type="{http://cfe.dgi.gub.uy}FechaType" minOccurs="0"/>
     *                             &lt;element name="PeridoHasta" type="{http://cfe.dgi.gub.uy}FechaType" minOccurs="0"/>
     *                             &lt;element name="MntBruto" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *                                   &lt;enumeration value="1"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="FmaPago">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
     *                                   &lt;enumeration value="1"/>
     *                                   &lt;enumeration value="2"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="FchVenc" type="{http://cfe.dgi.gub.uy}FechaType" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Emisor" type="{http://cfe.dgi.gub.uy}Emisor"/>
     *                   &lt;element name="Receptor" type="{http://cfe.dgi.gub.uy}Receptor_Tck" minOccurs="0"/>
     *                   &lt;element name="Totales" type="{http://cfe.dgi.gub.uy}Totales"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Detalle">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Item" type="{http://cfe.dgi.gub.uy}Item_Det_Fact" maxOccurs="700"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="SubTotInfo" type="{http://cfe.dgi.gub.uy}SubTotInfo" minOccurs="0"/>
     *         &lt;element name="DscRcgGlobal" type="{http://cfe.dgi.gub.uy}DscRcgGlobal" minOccurs="0"/>
     *         &lt;element name="MediosPago" type="{http://cfe.dgi.gub.uy}MediosPago" minOccurs="0"/>
     *         &lt;element name="Referencia" type="{http://cfe.dgi.gub.uy}ReferenciaEl" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "encabezado",
        "detalle",
        "subTotInfo",
        "dscRcgGlobal",
        "mediosPago",
        "referencia"
    })
    public static class ETck {

        @XmlElement(name = "Encabezado", required = true)
        protected CFEDefTypeX.ETck.Encabezado encabezado;
        @XmlElement(name = "Detalle", required = true)
        protected CFEDefTypeX.ETck.Detalle detalle;
        @XmlElement(name = "SubTotInfo")
        protected SubTotInfo subTotInfo;
        @XmlElement(name = "DscRcgGlobal")
        protected DscRcgGlobal dscRcgGlobal;
        @XmlElement(name = "MediosPago")
        protected MediosPago mediosPago;
        @XmlElement(name = "Referencia")
        protected ReferenciaEl referencia;

        /**
         * Gets the value of the encabezado property.
         * 
         * @return
         *     possible object is
         *     {@link CFEDefTypeX.ETck.Encabezado }
         *     
         */
        public CFEDefTypeX.ETck.Encabezado getEncabezado() {
            return encabezado;
        }

        /**
         * Sets the value of the encabezado property.
         * 
         * @param value
         *     allowed object is
         *     {@link CFEDefTypeX.ETck.Encabezado }
         *     
         */
        public void setEncabezado(CFEDefTypeX.ETck.Encabezado value) {
            this.encabezado = value;
        }

        /**
         * Gets the value of the detalle property.
         * 
         * @return
         *     possible object is
         *     {@link CFEDefTypeX.ETck.Detalle }
         *     
         */
        public CFEDefTypeX.ETck.Detalle getDetalle() {
            return detalle;
        }

        /**
         * Sets the value of the detalle property.
         * 
         * @param value
         *     allowed object is
         *     {@link CFEDefTypeX.ETck.Detalle }
         *     
         */
        public void setDetalle(CFEDefTypeX.ETck.Detalle value) {
            this.detalle = value;
        }

        /**
         * Gets the value of the subTotInfo property.
         * 
         * @return
         *     possible object is
         *     {@link SubTotInfo }
         *     
         */
        public SubTotInfo getSubTotInfo() {
            return subTotInfo;
        }

        /**
         * Sets the value of the subTotInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link SubTotInfo }
         *     
         */
        public void setSubTotInfo(SubTotInfo value) {
            this.subTotInfo = value;
        }

        /**
         * Gets the value of the dscRcgGlobal property.
         * 
         * @return
         *     possible object is
         *     {@link DscRcgGlobal }
         *     
         */
        public DscRcgGlobal getDscRcgGlobal() {
            return dscRcgGlobal;
        }

        /**
         * Sets the value of the dscRcgGlobal property.
         * 
         * @param value
         *     allowed object is
         *     {@link DscRcgGlobal }
         *     
         */
        public void setDscRcgGlobal(DscRcgGlobal value) {
            this.dscRcgGlobal = value;
        }

        /**
         * Gets the value of the mediosPago property.
         * 
         * @return
         *     possible object is
         *     {@link MediosPago }
         *     
         */
        public MediosPago getMediosPago() {
            return mediosPago;
        }

        /**
         * Sets the value of the mediosPago property.
         * 
         * @param value
         *     allowed object is
         *     {@link MediosPago }
         *     
         */
        public void setMediosPago(MediosPago value) {
            this.mediosPago = value;
        }

        /**
         * Gets the value of the referencia property.
         * 
         * @return
         *     possible object is
         *     {@link ReferenciaEl }
         *     
         */
        public ReferenciaEl getReferencia() {
            return referencia;
        }

        /**
         * Sets the value of the referencia property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReferenciaEl }
         *     
         */
        public void setReferencia(ReferenciaEl value) {
            this.referencia = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Item" type="{http://cfe.dgi.gub.uy}Item_Det_Fact" maxOccurs="700"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "item"
        })
        public static class Detalle {

            @XmlElement(name = "Item", required = true)
            protected List<ItemDetFact> item;

            /**
             * Gets the value of the item property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the item property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getItem().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ItemDetFact }
             * 
             * 
             */
            public List<ItemDetFact> getItem() {
                if (item == null) {
                    item = new ArrayList<ItemDetFact>();
                }
                return this.item;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="IdDoc">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="TipoCFE">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
         *                         &lt;enumeration value="101"/>
         *                         &lt;enumeration value="102"/>
         *                         &lt;enumeration value="103"/>
         *                         &lt;enumeration value="201"/>
         *                         &lt;enumeration value="202"/>
         *                         &lt;enumeration value="203"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="Serie" type="{http://cfe.dgi.gub.uy}SerieType"/>
         *                   &lt;element name="Nro" type="{http://cfe.dgi.gub.uy}NroCFEType"/>
         *                   &lt;element name="FchEmis" type="{http://cfe.dgi.gub.uy}FechaType"/>
         *                   &lt;element name="PeriodoDesde" type="{http://cfe.dgi.gub.uy}FechaType" minOccurs="0"/>
         *                   &lt;element name="PeridoHasta" type="{http://cfe.dgi.gub.uy}FechaType" minOccurs="0"/>
         *                   &lt;element name="MntBruto" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
         *                         &lt;enumeration value="1"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="FmaPago">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
         *                         &lt;enumeration value="1"/>
         *                         &lt;enumeration value="2"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="FchVenc" type="{http://cfe.dgi.gub.uy}FechaType" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Emisor" type="{http://cfe.dgi.gub.uy}Emisor"/>
         *         &lt;element name="Receptor" type="{http://cfe.dgi.gub.uy}Receptor_Tck" minOccurs="0"/>
         *         &lt;element name="Totales" type="{http://cfe.dgi.gub.uy}Totales"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "idDoc",
            "emisor",
            "receptor",
            "totales"
        })
        public static class Encabezado {

            @XmlElement(name = "IdDoc", required = true)
            protected CFEDefTypeX.ETck.Encabezado.IdDoc idDoc;
            @XmlElement(name = "Emisor", required = true)
            protected Emisor emisor;
            @XmlElement(name = "Receptor")
            protected ReceptorTck receptor;
            @XmlElement(name = "Totales", required = true)
            protected uy.gub.dgi.cfe.Totales totales;

            /**
             * Gets the value of the idDoc property.
             * 
             * @return
             *     possible object is
             *     {@link CFEDefTypeX.ETck.Encabezado.IdDoc }
             *     
             */
            public CFEDefTypeX.ETck.Encabezado.IdDoc getIdDoc() {
                return idDoc;
            }

            /**
             * Sets the value of the idDoc property.
             * 
             * @param value
             *     allowed object is
             *     {@link CFEDefTypeX.ETck.Encabezado.IdDoc }
             *     
             */
            public void setIdDoc(CFEDefTypeX.ETck.Encabezado.IdDoc value) {
                this.idDoc = value;
            }

            /**
             * Gets the value of the emisor property.
             * 
             * @return
             *     possible object is
             *     {@link Emisor }
             *     
             */
            public Emisor getEmisor() {
                return emisor;
            }

            /**
             * Sets the value of the emisor property.
             * 
             * @param value
             *     allowed object is
             *     {@link Emisor }
             *     
             */
            public void setEmisor(Emisor value) {
                this.emisor = value;
            }

            /**
             * Gets the value of the receptor property.
             * 
             * @return
             *     possible object is
             *     {@link ReceptorTck }
             *     
             */
            public ReceptorTck getReceptor() {
                return receptor;
            }

            /**
             * Sets the value of the receptor property.
             * 
             * @param value
             *     allowed object is
             *     {@link ReceptorTck }
             *     
             */
            public void setReceptor(ReceptorTck value) {
                this.receptor = value;
            }

            /**
             * Gets the value of the totales property.
             * 
             * @return
             *     possible object is
             *     {@link uy.gub.dgi.cfe.Totales }
             *     
             */
            public uy.gub.dgi.cfe.Totales getTotales() {
                return totales;
            }

            /**
             * Sets the value of the totales property.
             * 
             * @param value
             *     allowed object is
             *     {@link uy.gub.dgi.cfe.Totales }
             *     
             */
            public void setTotales(uy.gub.dgi.cfe.Totales value) {
                this.totales = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="TipoCFE">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
             *               &lt;enumeration value="101"/>
             *               &lt;enumeration value="102"/>
             *               &lt;enumeration value="103"/>
             *               &lt;enumeration value="201"/>
             *               &lt;enumeration value="202"/>
             *               &lt;enumeration value="203"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="Serie" type="{http://cfe.dgi.gub.uy}SerieType"/>
             *         &lt;element name="Nro" type="{http://cfe.dgi.gub.uy}NroCFEType"/>
             *         &lt;element name="FchEmis" type="{http://cfe.dgi.gub.uy}FechaType"/>
             *         &lt;element name="PeriodoDesde" type="{http://cfe.dgi.gub.uy}FechaType" minOccurs="0"/>
             *         &lt;element name="PeridoHasta" type="{http://cfe.dgi.gub.uy}FechaType" minOccurs="0"/>
             *         &lt;element name="MntBruto" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
             *               &lt;enumeration value="1"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="FmaPago">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
             *               &lt;enumeration value="1"/>
             *               &lt;enumeration value="2"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="FchVenc" type="{http://cfe.dgi.gub.uy}FechaType" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "tipoCFE",
                "serie",
                "nro",
                "fchEmis",
                "periodoDesde",
                "peridoHasta",
                "mntBruto",
                "fmaPago",
                "fchVenc"
            })
            public static class IdDoc {

                @XmlElement(name = "TipoCFE", required = true)
                protected BigInteger tipoCFE;
                @XmlElement(name = "Serie", required = true)
                protected String serie;
                @XmlElement(name = "Nro", required = true)
                protected BigInteger nro;
                @XmlElement(name = "FchEmis", required = true)
                protected XMLGregorianCalendar fchEmis;
                @XmlElement(name = "PeriodoDesde")
                protected XMLGregorianCalendar periodoDesde;
                @XmlElement(name = "PeridoHasta")
                protected XMLGregorianCalendar peridoHasta;
                @XmlElement(name = "MntBruto")
                protected BigInteger mntBruto;
                @XmlElement(name = "FmaPago", required = true)
                protected BigInteger fmaPago;
                @XmlElement(name = "FchVenc")
                protected XMLGregorianCalendar fchVenc;

                /**
                 * Gets the value of the tipoCFE property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getTipoCFE() {
                    return tipoCFE;
                }

                /**
                 * Sets the value of the tipoCFE property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setTipoCFE(BigInteger value) {
                    this.tipoCFE = value;
                }

                /**
                 * Gets the value of the serie property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSerie() {
                    return serie;
                }

                /**
                 * Sets the value of the serie property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSerie(String value) {
                    this.serie = value;
                }

                /**
                 * Gets the value of the nro property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getNro() {
                    return nro;
                }

                /**
                 * Sets the value of the nro property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setNro(BigInteger value) {
                    this.nro = value;
                }

                /**
                 * Gets the value of the fchEmis property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getFchEmis() {
                    return fchEmis;
                }

                /**
                 * Sets the value of the fchEmis property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setFchEmis(XMLGregorianCalendar value) {
                    this.fchEmis = value;
                }

                /**
                 * Gets the value of the periodoDesde property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getPeriodoDesde() {
                    return periodoDesde;
                }

                /**
                 * Sets the value of the periodoDesde property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setPeriodoDesde(XMLGregorianCalendar value) {
                    this.periodoDesde = value;
                }

                /**
                 * Gets the value of the peridoHasta property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getPeridoHasta() {
                    return peridoHasta;
                }

                /**
                 * Sets the value of the peridoHasta property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setPeridoHasta(XMLGregorianCalendar value) {
                    this.peridoHasta = value;
                }

                /**
                 * Gets the value of the mntBruto property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getMntBruto() {
                    return mntBruto;
                }

                /**
                 * Sets the value of the mntBruto property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setMntBruto(BigInteger value) {
                    this.mntBruto = value;
                }

                /**
                 * Gets the value of the fmaPago property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getFmaPago() {
                    return fmaPago;
                }

                /**
                 * Sets the value of the fmaPago property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setFmaPago(BigInteger value) {
                    this.fmaPago = value;
                }

                /**
                 * Gets the value of the fchVenc property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getFchVenc() {
                    return fchVenc;
                }

                /**
                 * Sets the value of the fchVenc property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setFchVenc(XMLGregorianCalendar value) {
                    this.fchVenc = value;
                }

            }

        }

    }

}
