//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.14 at 10:23:17 AM UYST 
//


package uy.gub.dgi.cfe;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uy.gub.dgi.cfe package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uy.gub.dgi.cfe
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EnvioCFE }
     * 
     */
    public EnvioCFE createEnvioCFE() {
        return new EnvioCFE();
    }

    /**
     * Create an instance of {@link ItemDetFact }
     * 
     */
    public ItemDetFact createItemDetFact() {
        return new ItemDetFact();
    }

    /**
     * Create an instance of {@link ItemRem }
     * 
     */
    public ItemRem createItemRem() {
        return new ItemRem();
    }

    /**
     * Create an instance of {@link TotalesResg }
     * 
     */
    public TotalesResg createTotalesResg() {
        return new TotalesResg();
    }

    /**
     * Create an instance of {@link Referencia }
     * 
     */
    public Referencia createReferencia() {
        return new Referencia();
    }

    /**
     * Create an instance of {@link MediosPago }
     * 
     */
    public MediosPago createMediosPago() {
        return new MediosPago();
    }

    /**
     * Create an instance of {@link DscRcgGlobal }
     * 
     */
    public DscRcgGlobal createDscRcgGlobal() {
        return new DscRcgGlobal();
    }

    /**
     * Create an instance of {@link uy.gub.dgi.cfe.Totales }
     * 
     */
    public uy.gub.dgi.cfe.Totales createTotales() {
        return new uy.gub.dgi.cfe.Totales();
    }

    /**
     * Create an instance of {@link SubTotInfo }
     * 
     */
    public SubTotInfo createSubTotInfo() {
        return new SubTotInfo();
    }

    /**
     * Create an instance of {@link CFEDefType }
     * 
     */
    public CFEDefType createCFEDefType() {
        return new CFEDefType();
    }

    /**
     * Create an instance of {@link CFEDefType.EResg }
     * 
     */
    public CFEDefType.EResg createCFEDefTypeEResg() {
        return new CFEDefType.EResg();
    }

    /**
     * Create an instance of {@link CFEDefType.ERem }
     * 
     */
    public CFEDefType.ERem createCFEDefTypeERem() {
        return new CFEDefType.ERem();
    }

    /**
     * Create an instance of {@link CFEDefType.ERem.Encabezado }
     * 
     */
    public CFEDefType.ERem.Encabezado createCFEDefTypeERemEncabezado() {
        return new CFEDefType.ERem.Encabezado();
    }

    /**
     * Create an instance of {@link CFEDefType.EFact }
     * 
     */
    public CFEDefType.EFact createCFEDefTypeEFact() {
        return new CFEDefType.EFact();
    }

    /**
     * Create an instance of {@link CFEDefType.ETck }
     * 
     */
    public CFEDefType.ETck createCFEDefTypeETck() {
        return new CFEDefType.ETck();
    }

    /**
     * Create an instance of {@link EnvioCFE.Caratula }
     * 
     */
    public EnvioCFE.Caratula createEnvioCFECaratula() {
        return new EnvioCFE.Caratula();
    }

    /**
     * Create an instance of {@link RetPercResg }
     * 
     */
    public RetPercResg createRetPercResg() {
        return new RetPercResg();
    }

    /**
     * Create an instance of {@link RechazoSobreType }
     * 
     */
    public RechazoSobreType createRechazoSobreType() {
        return new RechazoSobreType();
    }

    /**
     * Create an instance of {@link IdDocRem }
     * 
     */
    public IdDocRem createIdDocRem() {
        return new IdDocRem();
    }

    /**
     * Create an instance of {@link IdDocFact }
     * 
     */
    public IdDocFact createIdDocFact() {
        return new IdDocFact();
    }

    /**
     * Create an instance of {@link ReceptorTck }
     * 
     */
    public ReceptorTck createReceptorTck() {
        return new ReceptorTck();
    }

    /**
     * Create an instance of {@link ReceptorResg }
     * 
     */
    public ReceptorResg createReceptorResg() {
        return new ReceptorResg();
    }

    /**
     * Create an instance of {@link Emisor }
     * 
     */
    public Emisor createEmisor() {
        return new Emisor();
    }

    /**
     * Create an instance of {@link ReceptorRem }
     * 
     */
    public ReceptorRem createReceptorRem() {
        return new ReceptorRem();
    }

    /**
     * Create an instance of {@link IdDocTck }
     * 
     */
    public IdDocTck createIdDocTck() {
        return new IdDocTck();
    }

    /**
     * Create an instance of {@link IdDocResg }
     * 
     */
    public IdDocResg createIdDocResg() {
        return new IdDocResg();
    }

    /**
     * Create an instance of {@link ItemResg }
     * 
     */
    public ItemResg createItemResg() {
        return new ItemResg();
    }

    /**
     * Create an instance of {@link CAEDataType }
     * 
     */
    public CAEDataType createCAEDataType() {
        return new CAEDataType();
    }

    /**
     * Create an instance of {@link RetPerc }
     * 
     */
    public RetPerc createRetPerc() {
        return new RetPerc();
    }

    /**
     * Create an instance of {@link RechazoRepType }
     * 
     */
    public RechazoRepType createRechazoRepType() {
        return new RechazoRepType();
    }

    /**
     * Create an instance of {@link ReceptorFact }
     * 
     */
    public ReceptorFact createReceptorFact() {
        return new ReceptorFact();
    }

    /**
     * Create an instance of {@link ObsCFCType }
     * 
     */
    public ObsCFCType createObsCFCType() {
        return new ObsCFCType();
    }

    /**
     * Create an instance of {@link RechazoCFEDGIType }
     * 
     */
    public RechazoCFEDGIType createRechazoCFEDGIType() {
        return new RechazoCFEDGIType();
    }

    /**
     * Create an instance of {@link RechazoCFEPartesType }
     * 
     */
    public RechazoCFEPartesType createRechazoCFEPartesType() {
        return new RechazoCFEPartesType();
    }

    /**
     * Create an instance of {@link ItemDetFact.CodItem }
     * 
     */
    public ItemDetFact.CodItem createItemDetFactCodItem() {
        return new ItemDetFact.CodItem();
    }

    /**
     * Create an instance of {@link ItemDetFact.SubDescuento }
     * 
     */
    public ItemDetFact.SubDescuento createItemDetFactSubDescuento() {
        return new ItemDetFact.SubDescuento();
    }

    /**
     * Create an instance of {@link ItemDetFact.SubRecargo }
     * 
     */
    public ItemDetFact.SubRecargo createItemDetFactSubRecargo() {
        return new ItemDetFact.SubRecargo();
    }

    /**
     * Create an instance of {@link ItemRem.CodItem }
     * 
     */
    public ItemRem.CodItem createItemRemCodItem() {
        return new ItemRem.CodItem();
    }

    /**
     * Create an instance of {@link TotalesResg.RetencPercep }
     * 
     */
    public TotalesResg.RetencPercep createTotalesResgRetencPercep() {
        return new TotalesResg.RetencPercep();
    }

    /**
     * Create an instance of {@link Referencia.ReferenciaElement }
     * 
     */
    public Referencia.ReferenciaElement createReferenciaReferenciaElement() {
        return new Referencia.ReferenciaElement();
    }

    /**
     * Create an instance of {@link MediosPago.MedioPago }
     * 
     */
    public MediosPago.MedioPago createMediosPagoMedioPago() {
        return new MediosPago.MedioPago();
    }

    /**
     * Create an instance of {@link DscRcgGlobal.DRGItem }
     * 
     */
    public DscRcgGlobal.DRGItem createDscRcgGlobalDRGItem() {
        return new DscRcgGlobal.DRGItem();
    }

    /**
     * Create an instance of {@link uy.gub.dgi.cfe.Totales.RetencPercep }
     * 
     */
    public uy.gub.dgi.cfe.Totales.RetencPercep createTotalesRetencPercep() {
        return new uy.gub.dgi.cfe.Totales.RetencPercep();
    }

    /**
     * Create an instance of {@link SubTotInfo.STIItem }
     * 
     */
    public SubTotInfo.STIItem createSubTotInfoSTIItem() {
        return new SubTotInfo.STIItem();
    }

    /**
     * Create an instance of {@link CFEDefType.EResg.Encabezado }
     * 
     */
    public CFEDefType.EResg.Encabezado createCFEDefTypeEResgEncabezado() {
        return new CFEDefType.EResg.Encabezado();
    }

    /**
     * Create an instance of {@link CFEDefType.EResg.Detalle }
     * 
     */
    public CFEDefType.EResg.Detalle createCFEDefTypeEResgDetalle() {
        return new CFEDefType.EResg.Detalle();
    }

    /**
     * Create an instance of {@link CFEDefType.ERem.Detalle }
     * 
     */
    public CFEDefType.ERem.Detalle createCFEDefTypeERemDetalle() {
        return new CFEDefType.ERem.Detalle();
    }

    /**
     * Create an instance of {@link CFEDefType.ERem.Encabezado.Totales }
     * 
     */
    public CFEDefType.ERem.Encabezado.Totales createCFEDefTypeERemEncabezadoTotales() {
        return new CFEDefType.ERem.Encabezado.Totales();
    }

    /**
     * Create an instance of {@link CFEDefType.EFact.Encabezado }
     * 
     */
    public CFEDefType.EFact.Encabezado createCFEDefTypeEFactEncabezado() {
        return new CFEDefType.EFact.Encabezado();
    }

    /**
     * Create an instance of {@link CFEDefType.EFact.Detalle }
     * 
     */
    public CFEDefType.EFact.Detalle createCFEDefTypeEFactDetalle() {
        return new CFEDefType.EFact.Detalle();
    }

    /**
     * Create an instance of {@link CFEDefType.ETck.Encabezado }
     * 
     */
    public CFEDefType.ETck.Encabezado createCFEDefTypeETckEncabezado() {
        return new CFEDefType.ETck.Encabezado();
    }

    /**
     * Create an instance of {@link CFEDefType.ETck.Detalle }
     * 
     */
    public CFEDefType.ETck.Detalle createCFEDefTypeETckDetalle() {
        return new CFEDefType.ETck.Detalle();
    }

}
