//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.14 at 10:23:17 AM UYST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://cfe.dgi.gub.uy", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uy.gub.dgi.cfe;
