//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.18 at 12:19:08 PM UYST 
//


package uy.gub.dgi.cfe;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.w3._2000._09.xmldsig.SignatureType;


/**
 * <p>Java class for ReporteDefType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReporteDefType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Caratula">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RUCEmisor" type="{http://cfe.dgi.gub.uy}RUCType"/>
 *                   &lt;element name="FechaResumen">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://cfe.dgi.gub.uy}FechaType">
 *                         &lt;minInclusive value="2011-10-01"/>
 *                         &lt;maxInclusive value="2050-12-31"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="IDEmisor" type="{http://cfe.dgi.gub.uy}IDRecEmiType" minOccurs="0"/>
 *                   &lt;element name="SecEnvio">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;minInclusive value="0"/>
 *                         &lt;totalDigits value="2"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="TmstFirmaEnv" type="{http://cfe.dgi.gub.uy}FechaHoraType"/>
 *                   &lt;element name="CantComprobantes">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;minInclusive value="0"/>
 *                         &lt;totalDigits value="10"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="version" use="required" fixed="1.0">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;maxLength value="3"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Rsmn_Tck" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TipoComp">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
 *                         &lt;enumeration value="101"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Tck"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Rsmn_Tck_Nota_Credito" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TipoComp">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
 *                         &lt;enumeration value="102"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Tck"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Rsmn_Tck_Nota_Debito" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TipoComp">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
 *                         &lt;enumeration value="103"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Tck"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Rsmn_Tck_Cont" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TipoComp">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
 *                         &lt;enumeration value="201"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Tck_Cont"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Rsmn_Tck_Cont_Nota_Credito" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TipoComp">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
 *                         &lt;enumeration value="202"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Tck_Cont"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Rsmn_Tck_Cont_Nota_Debito" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TipoComp">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
 *                         &lt;enumeration value="203"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Tck_Cont"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Rsmn_Fac" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TipoComp">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
 *                         &lt;enumeration value="111"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Fac"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Rsmn_Fac_Nota_Credito" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TipoComp">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
 *                         &lt;enumeration value="112"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Fac"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Rsmn_Fac_Nota_Debito" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TipoComp">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
 *                         &lt;enumeration value="113"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Fac"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Rsmn_Fac_Cont" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TipoComp">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
 *                         &lt;enumeration value="211"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Fac_Cont"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Rsmn_Fac_Cont_Nota_Credito" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TipoComp">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
 *                         &lt;enumeration value="212"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Fac_Cont"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Rsmn_Fac_Cont_Nota_Debito" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TipoComp">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
 *                         &lt;enumeration value="213"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Fac_Cont"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Rsmn_Rem" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TipoComp">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
 *                         &lt;enumeration value="181"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Rem"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Rsmn_Rem_Cont" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TipoComp">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
 *                         &lt;enumeration value="281"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Rem_Cont"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Rsmn_Resg" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TipoComp">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
 *                         &lt;enumeration value="182"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Resg"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Rsmn_Resg_Cont" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TipoComp">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
 *                         &lt;enumeration value="282"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Resg_Cont"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReporteDefType", propOrder = {
    "caratula",
    "rsmnTck",
    "rsmnTckNotaCredito",
    "rsmnTckNotaDebito",
    "rsmnTckCont",
    "rsmnTckContNotaCredito",
    "rsmnTckContNotaDebito",
    "rsmnFac",
    "rsmnFacNotaCredito",
    "rsmnFacNotaDebito",
    "rsmnFacCont",
    "rsmnFacContNotaCredito",
    "rsmnFacContNotaDebito",
    "rsmnRem",
    "rsmnRemCont",
    "rsmnResg",
    "rsmnResgCont",
    "signature"
})
public class ReporteDefType {

    @XmlElement(name = "Caratula", required = true)
    protected ReporteDefType.Caratula caratula;
    @XmlElement(name = "Rsmn_Tck")
    protected ReporteDefType.RsmnTck rsmnTck;
    @XmlElement(name = "Rsmn_Tck_Nota_Credito")
    protected ReporteDefType.RsmnTckNotaCredito rsmnTckNotaCredito;
    @XmlElement(name = "Rsmn_Tck_Nota_Debito")
    protected ReporteDefType.RsmnTckNotaDebito rsmnTckNotaDebito;
    @XmlElement(name = "Rsmn_Tck_Cont")
    protected ReporteDefType.RsmnTckCont rsmnTckCont;
    @XmlElement(name = "Rsmn_Tck_Cont_Nota_Credito")
    protected ReporteDefType.RsmnTckContNotaCredito rsmnTckContNotaCredito;
    @XmlElement(name = "Rsmn_Tck_Cont_Nota_Debito")
    protected ReporteDefType.RsmnTckContNotaDebito rsmnTckContNotaDebito;
    @XmlElement(name = "Rsmn_Fac")
    protected ReporteDefType.RsmnFac rsmnFac;
    @XmlElement(name = "Rsmn_Fac_Nota_Credito")
    protected ReporteDefType.RsmnFacNotaCredito rsmnFacNotaCredito;
    @XmlElement(name = "Rsmn_Fac_Nota_Debito")
    protected ReporteDefType.RsmnFacNotaDebito rsmnFacNotaDebito;
    @XmlElement(name = "Rsmn_Fac_Cont")
    protected ReporteDefType.RsmnFacCont rsmnFacCont;
    @XmlElement(name = "Rsmn_Fac_Cont_Nota_Credito")
    protected ReporteDefType.RsmnFacContNotaCredito rsmnFacContNotaCredito;
    @XmlElement(name = "Rsmn_Fac_Cont_Nota_Debito")
    protected ReporteDefType.RsmnFacContNotaDebito rsmnFacContNotaDebito;
    @XmlElement(name = "Rsmn_Rem")
    protected ReporteDefType.RsmnRem rsmnRem;
    @XmlElement(name = "Rsmn_Rem_Cont")
    protected ReporteDefType.RsmnRemCont rsmnRemCont;
    @XmlElement(name = "Rsmn_Resg")
    protected ReporteDefType.RsmnResg rsmnResg;
    @XmlElement(name = "Rsmn_Resg_Cont")
    protected ReporteDefType.RsmnResgCont rsmnResgCont;
    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#", required = true)
    protected SignatureType signature;

    /**
     * Gets the value of the caratula property.
     * 
     * @return
     *     possible object is
     *     {@link ReporteDefType.Caratula }
     *     
     */
    public ReporteDefType.Caratula getCaratula() {
        return caratula;
    }

    /**
     * Sets the value of the caratula property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReporteDefType.Caratula }
     *     
     */
    public void setCaratula(ReporteDefType.Caratula value) {
        this.caratula = value;
    }

    /**
     * Gets the value of the rsmnTck property.
     * 
     * @return
     *     possible object is
     *     {@link ReporteDefType.RsmnTck }
     *     
     */
    public ReporteDefType.RsmnTck getRsmnTck() {
        return rsmnTck;
    }

    /**
     * Sets the value of the rsmnTck property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReporteDefType.RsmnTck }
     *     
     */
    public void setRsmnTck(ReporteDefType.RsmnTck value) {
        this.rsmnTck = value;
    }

    /**
     * Gets the value of the rsmnTckNotaCredito property.
     * 
     * @return
     *     possible object is
     *     {@link ReporteDefType.RsmnTckNotaCredito }
     *     
     */
    public ReporteDefType.RsmnTckNotaCredito getRsmnTckNotaCredito() {
        return rsmnTckNotaCredito;
    }

    /**
     * Sets the value of the rsmnTckNotaCredito property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReporteDefType.RsmnTckNotaCredito }
     *     
     */
    public void setRsmnTckNotaCredito(ReporteDefType.RsmnTckNotaCredito value) {
        this.rsmnTckNotaCredito = value;
    }

    /**
     * Gets the value of the rsmnTckNotaDebito property.
     * 
     * @return
     *     possible object is
     *     {@link ReporteDefType.RsmnTckNotaDebito }
     *     
     */
    public ReporteDefType.RsmnTckNotaDebito getRsmnTckNotaDebito() {
        return rsmnTckNotaDebito;
    }

    /**
     * Sets the value of the rsmnTckNotaDebito property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReporteDefType.RsmnTckNotaDebito }
     *     
     */
    public void setRsmnTckNotaDebito(ReporteDefType.RsmnTckNotaDebito value) {
        this.rsmnTckNotaDebito = value;
    }

    /**
     * Gets the value of the rsmnTckCont property.
     * 
     * @return
     *     possible object is
     *     {@link ReporteDefType.RsmnTckCont }
     *     
     */
    public ReporteDefType.RsmnTckCont getRsmnTckCont() {
        return rsmnTckCont;
    }

    /**
     * Sets the value of the rsmnTckCont property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReporteDefType.RsmnTckCont }
     *     
     */
    public void setRsmnTckCont(ReporteDefType.RsmnTckCont value) {
        this.rsmnTckCont = value;
    }

    /**
     * Gets the value of the rsmnTckContNotaCredito property.
     * 
     * @return
     *     possible object is
     *     {@link ReporteDefType.RsmnTckContNotaCredito }
     *     
     */
    public ReporteDefType.RsmnTckContNotaCredito getRsmnTckContNotaCredito() {
        return rsmnTckContNotaCredito;
    }

    /**
     * Sets the value of the rsmnTckContNotaCredito property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReporteDefType.RsmnTckContNotaCredito }
     *     
     */
    public void setRsmnTckContNotaCredito(ReporteDefType.RsmnTckContNotaCredito value) {
        this.rsmnTckContNotaCredito = value;
    }

    /**
     * Gets the value of the rsmnTckContNotaDebito property.
     * 
     * @return
     *     possible object is
     *     {@link ReporteDefType.RsmnTckContNotaDebito }
     *     
     */
    public ReporteDefType.RsmnTckContNotaDebito getRsmnTckContNotaDebito() {
        return rsmnTckContNotaDebito;
    }

    /**
     * Sets the value of the rsmnTckContNotaDebito property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReporteDefType.RsmnTckContNotaDebito }
     *     
     */
    public void setRsmnTckContNotaDebito(ReporteDefType.RsmnTckContNotaDebito value) {
        this.rsmnTckContNotaDebito = value;
    }

    /**
     * Gets the value of the rsmnFac property.
     * 
     * @return
     *     possible object is
     *     {@link ReporteDefType.RsmnFac }
     *     
     */
    public ReporteDefType.RsmnFac getRsmnFac() {
        return rsmnFac;
    }

    /**
     * Sets the value of the rsmnFac property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReporteDefType.RsmnFac }
     *     
     */
    public void setRsmnFac(ReporteDefType.RsmnFac value) {
        this.rsmnFac = value;
    }

    /**
     * Gets the value of the rsmnFacNotaCredito property.
     * 
     * @return
     *     possible object is
     *     {@link ReporteDefType.RsmnFacNotaCredito }
     *     
     */
    public ReporteDefType.RsmnFacNotaCredito getRsmnFacNotaCredito() {
        return rsmnFacNotaCredito;
    }

    /**
     * Sets the value of the rsmnFacNotaCredito property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReporteDefType.RsmnFacNotaCredito }
     *     
     */
    public void setRsmnFacNotaCredito(ReporteDefType.RsmnFacNotaCredito value) {
        this.rsmnFacNotaCredito = value;
    }

    /**
     * Gets the value of the rsmnFacNotaDebito property.
     * 
     * @return
     *     possible object is
     *     {@link ReporteDefType.RsmnFacNotaDebito }
     *     
     */
    public ReporteDefType.RsmnFacNotaDebito getRsmnFacNotaDebito() {
        return rsmnFacNotaDebito;
    }

    /**
     * Sets the value of the rsmnFacNotaDebito property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReporteDefType.RsmnFacNotaDebito }
     *     
     */
    public void setRsmnFacNotaDebito(ReporteDefType.RsmnFacNotaDebito value) {
        this.rsmnFacNotaDebito = value;
    }

    /**
     * Gets the value of the rsmnFacCont property.
     * 
     * @return
     *     possible object is
     *     {@link ReporteDefType.RsmnFacCont }
     *     
     */
    public ReporteDefType.RsmnFacCont getRsmnFacCont() {
        return rsmnFacCont;
    }

    /**
     * Sets the value of the rsmnFacCont property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReporteDefType.RsmnFacCont }
     *     
     */
    public void setRsmnFacCont(ReporteDefType.RsmnFacCont value) {
        this.rsmnFacCont = value;
    }

    /**
     * Gets the value of the rsmnFacContNotaCredito property.
     * 
     * @return
     *     possible object is
     *     {@link ReporteDefType.RsmnFacContNotaCredito }
     *     
     */
    public ReporteDefType.RsmnFacContNotaCredito getRsmnFacContNotaCredito() {
        return rsmnFacContNotaCredito;
    }

    /**
     * Sets the value of the rsmnFacContNotaCredito property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReporteDefType.RsmnFacContNotaCredito }
     *     
     */
    public void setRsmnFacContNotaCredito(ReporteDefType.RsmnFacContNotaCredito value) {
        this.rsmnFacContNotaCredito = value;
    }

    /**
     * Gets the value of the rsmnFacContNotaDebito property.
     * 
     * @return
     *     possible object is
     *     {@link ReporteDefType.RsmnFacContNotaDebito }
     *     
     */
    public ReporteDefType.RsmnFacContNotaDebito getRsmnFacContNotaDebito() {
        return rsmnFacContNotaDebito;
    }

    /**
     * Sets the value of the rsmnFacContNotaDebito property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReporteDefType.RsmnFacContNotaDebito }
     *     
     */
    public void setRsmnFacContNotaDebito(ReporteDefType.RsmnFacContNotaDebito value) {
        this.rsmnFacContNotaDebito = value;
    }

    /**
     * Gets the value of the rsmnRem property.
     * 
     * @return
     *     possible object is
     *     {@link ReporteDefType.RsmnRem }
     *     
     */
    public ReporteDefType.RsmnRem getRsmnRem() {
        return rsmnRem;
    }

    /**
     * Sets the value of the rsmnRem property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReporteDefType.RsmnRem }
     *     
     */
    public void setRsmnRem(ReporteDefType.RsmnRem value) {
        this.rsmnRem = value;
    }

    /**
     * Gets the value of the rsmnRemCont property.
     * 
     * @return
     *     possible object is
     *     {@link ReporteDefType.RsmnRemCont }
     *     
     */
    public ReporteDefType.RsmnRemCont getRsmnRemCont() {
        return rsmnRemCont;
    }

    /**
     * Sets the value of the rsmnRemCont property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReporteDefType.RsmnRemCont }
     *     
     */
    public void setRsmnRemCont(ReporteDefType.RsmnRemCont value) {
        this.rsmnRemCont = value;
    }

    /**
     * Gets the value of the rsmnResg property.
     * 
     * @return
     *     possible object is
     *     {@link ReporteDefType.RsmnResg }
     *     
     */
    public ReporteDefType.RsmnResg getRsmnResg() {
        return rsmnResg;
    }

    /**
     * Sets the value of the rsmnResg property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReporteDefType.RsmnResg }
     *     
     */
    public void setRsmnResg(ReporteDefType.RsmnResg value) {
        this.rsmnResg = value;
    }

    /**
     * Gets the value of the rsmnResgCont property.
     * 
     * @return
     *     possible object is
     *     {@link ReporteDefType.RsmnResgCont }
     *     
     */
    public ReporteDefType.RsmnResgCont getRsmnResgCont() {
        return rsmnResgCont;
    }

    /**
     * Sets the value of the rsmnResgCont property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReporteDefType.RsmnResgCont }
     *     
     */
    public void setRsmnResgCont(ReporteDefType.RsmnResgCont value) {
        this.rsmnResgCont = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RUCEmisor" type="{http://cfe.dgi.gub.uy}RUCType"/>
     *         &lt;element name="FechaResumen">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://cfe.dgi.gub.uy}FechaType">
     *               &lt;minInclusive value="2011-10-01"/>
     *               &lt;maxInclusive value="2050-12-31"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="IDEmisor" type="{http://cfe.dgi.gub.uy}IDRecEmiType" minOccurs="0"/>
     *         &lt;element name="SecEnvio">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *               &lt;minInclusive value="0"/>
     *               &lt;totalDigits value="2"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="TmstFirmaEnv" type="{http://cfe.dgi.gub.uy}FechaHoraType"/>
     *         &lt;element name="CantComprobantes">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *               &lt;minInclusive value="0"/>
     *               &lt;totalDigits value="10"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="version" use="required" fixed="1.0">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;maxLength value="3"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rucEmisor",
        "fechaResumen",
        "idEmisor",
        "secEnvio",
        "tmstFirmaEnv",
        "cantComprobantes"
    })
    public static class Caratula {

        @XmlElement(name = "RUCEmisor", required = true)
        protected String rucEmisor;
        @XmlElement(name = "FechaResumen", required = true)
        protected XMLGregorianCalendar fechaResumen;
        @XmlElement(name = "IDEmisor")
        protected BigInteger idEmisor;
        @XmlElement(name = "SecEnvio", required = true)
        protected BigInteger secEnvio;
        @XmlElement(name = "TmstFirmaEnv", required = true)
        protected XMLGregorianCalendar tmstFirmaEnv;
        @XmlElement(name = "CantComprobantes", required = true)
        protected BigInteger cantComprobantes;
        @XmlAttribute(name = "version", required = true)
        protected String version;

        /**
         * Gets the value of the rucEmisor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRUCEmisor() {
            return rucEmisor;
        }

        /**
         * Sets the value of the rucEmisor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRUCEmisor(String value) {
            this.rucEmisor = value;
        }

        /**
         * Gets the value of the fechaResumen property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFechaResumen() {
            return fechaResumen;
        }

        /**
         * Sets the value of the fechaResumen property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFechaResumen(XMLGregorianCalendar value) {
            this.fechaResumen = value;
        }

        /**
         * Gets the value of the idEmisor property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getIDEmisor() {
            return idEmisor;
        }

        /**
         * Sets the value of the idEmisor property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setIDEmisor(BigInteger value) {
            this.idEmisor = value;
        }

        /**
         * Gets the value of the secEnvio property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getSecEnvio() {
            return secEnvio;
        }

        /**
         * Sets the value of the secEnvio property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setSecEnvio(BigInteger value) {
            this.secEnvio = value;
        }

        /**
         * Gets the value of the tmstFirmaEnv property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTmstFirmaEnv() {
            return tmstFirmaEnv;
        }

        /**
         * Sets the value of the tmstFirmaEnv property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTmstFirmaEnv(XMLGregorianCalendar value) {
            this.tmstFirmaEnv = value;
        }

        /**
         * Gets the value of the cantComprobantes property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCantComprobantes() {
            return cantComprobantes;
        }

        /**
         * Sets the value of the cantComprobantes property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCantComprobantes(BigInteger value) {
            this.cantComprobantes = value;
        }

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            if (version == null) {
                return "1.0";
            } else {
                return version;
            }
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TipoComp">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
     *               &lt;enumeration value="111"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Fac"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipoComp",
        "rsmnData"
    })
    public static class RsmnFac {

        @XmlElement(name = "TipoComp", required = true)
        protected BigInteger tipoComp;
        @XmlElement(name = "RsmnData", required = true)
        protected RsmnDataFac rsmnData;

        /**
         * Gets the value of the tipoComp property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTipoComp() {
            return tipoComp;
        }

        /**
         * Sets the value of the tipoComp property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTipoComp(BigInteger value) {
            this.tipoComp = value;
        }

        /**
         * Gets the value of the rsmnData property.
         * 
         * @return
         *     possible object is
         *     {@link RsmnDataFac }
         *     
         */
        public RsmnDataFac getRsmnData() {
            return rsmnData;
        }

        /**
         * Sets the value of the rsmnData property.
         * 
         * @param value
         *     allowed object is
         *     {@link RsmnDataFac }
         *     
         */
        public void setRsmnData(RsmnDataFac value) {
            this.rsmnData = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TipoComp">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
     *               &lt;enumeration value="211"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Fac_Cont"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipoComp",
        "rsmnData"
    })
    public static class RsmnFacCont {

        @XmlElement(name = "TipoComp", required = true)
        protected BigInteger tipoComp;
        @XmlElement(name = "RsmnData", required = true)
        protected RsmnDataFacCont rsmnData;

        /**
         * Gets the value of the tipoComp property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTipoComp() {
            return tipoComp;
        }

        /**
         * Sets the value of the tipoComp property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTipoComp(BigInteger value) {
            this.tipoComp = value;
        }

        /**
         * Gets the value of the rsmnData property.
         * 
         * @return
         *     possible object is
         *     {@link RsmnDataFacCont }
         *     
         */
        public RsmnDataFacCont getRsmnData() {
            return rsmnData;
        }

        /**
         * Sets the value of the rsmnData property.
         * 
         * @param value
         *     allowed object is
         *     {@link RsmnDataFacCont }
         *     
         */
        public void setRsmnData(RsmnDataFacCont value) {
            this.rsmnData = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TipoComp">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
     *               &lt;enumeration value="212"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Fac_Cont"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipoComp",
        "rsmnData"
    })
    public static class RsmnFacContNotaCredito {

        @XmlElement(name = "TipoComp", required = true)
        protected BigInteger tipoComp;
        @XmlElement(name = "RsmnData", required = true)
        protected RsmnDataFacCont rsmnData;

        /**
         * Gets the value of the tipoComp property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTipoComp() {
            return tipoComp;
        }

        /**
         * Sets the value of the tipoComp property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTipoComp(BigInteger value) {
            this.tipoComp = value;
        }

        /**
         * Gets the value of the rsmnData property.
         * 
         * @return
         *     possible object is
         *     {@link RsmnDataFacCont }
         *     
         */
        public RsmnDataFacCont getRsmnData() {
            return rsmnData;
        }

        /**
         * Sets the value of the rsmnData property.
         * 
         * @param value
         *     allowed object is
         *     {@link RsmnDataFacCont }
         *     
         */
        public void setRsmnData(RsmnDataFacCont value) {
            this.rsmnData = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TipoComp">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
     *               &lt;enumeration value="213"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Fac_Cont"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipoComp",
        "rsmnData"
    })
    public static class RsmnFacContNotaDebito {

        @XmlElement(name = "TipoComp", required = true)
        protected BigInteger tipoComp;
        @XmlElement(name = "RsmnData", required = true)
        protected RsmnDataFacCont rsmnData;

        /**
         * Gets the value of the tipoComp property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTipoComp() {
            return tipoComp;
        }

        /**
         * Sets the value of the tipoComp property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTipoComp(BigInteger value) {
            this.tipoComp = value;
        }

        /**
         * Gets the value of the rsmnData property.
         * 
         * @return
         *     possible object is
         *     {@link RsmnDataFacCont }
         *     
         */
        public RsmnDataFacCont getRsmnData() {
            return rsmnData;
        }

        /**
         * Sets the value of the rsmnData property.
         * 
         * @param value
         *     allowed object is
         *     {@link RsmnDataFacCont }
         *     
         */
        public void setRsmnData(RsmnDataFacCont value) {
            this.rsmnData = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TipoComp">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
     *               &lt;enumeration value="112"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Fac"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipoComp",
        "rsmnData"
    })
    public static class RsmnFacNotaCredito {

        @XmlElement(name = "TipoComp", required = true)
        protected BigInteger tipoComp;
        @XmlElement(name = "RsmnData", required = true)
        protected RsmnDataFac rsmnData;

        /**
         * Gets the value of the tipoComp property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTipoComp() {
            return tipoComp;
        }

        /**
         * Sets the value of the tipoComp property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTipoComp(BigInteger value) {
            this.tipoComp = value;
        }

        /**
         * Gets the value of the rsmnData property.
         * 
         * @return
         *     possible object is
         *     {@link RsmnDataFac }
         *     
         */
        public RsmnDataFac getRsmnData() {
            return rsmnData;
        }

        /**
         * Sets the value of the rsmnData property.
         * 
         * @param value
         *     allowed object is
         *     {@link RsmnDataFac }
         *     
         */
        public void setRsmnData(RsmnDataFac value) {
            this.rsmnData = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TipoComp">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
     *               &lt;enumeration value="113"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Fac"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipoComp",
        "rsmnData"
    })
    public static class RsmnFacNotaDebito {

        @XmlElement(name = "TipoComp", required = true)
        protected BigInteger tipoComp;
        @XmlElement(name = "RsmnData", required = true)
        protected RsmnDataFac rsmnData;

        /**
         * Gets the value of the tipoComp property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTipoComp() {
            return tipoComp;
        }

        /**
         * Sets the value of the tipoComp property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTipoComp(BigInteger value) {
            this.tipoComp = value;
        }

        /**
         * Gets the value of the rsmnData property.
         * 
         * @return
         *     possible object is
         *     {@link RsmnDataFac }
         *     
         */
        public RsmnDataFac getRsmnData() {
            return rsmnData;
        }

        /**
         * Sets the value of the rsmnData property.
         * 
         * @param value
         *     allowed object is
         *     {@link RsmnDataFac }
         *     
         */
        public void setRsmnData(RsmnDataFac value) {
            this.rsmnData = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TipoComp">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
     *               &lt;enumeration value="181"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Rem"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipoComp",
        "rsmnData"
    })
    public static class RsmnRem {

        @XmlElement(name = "TipoComp", required = true)
        protected BigInteger tipoComp;
        @XmlElement(name = "RsmnData", required = true)
        protected RsmnDataRem rsmnData;

        /**
         * Gets the value of the tipoComp property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTipoComp() {
            return tipoComp;
        }

        /**
         * Sets the value of the tipoComp property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTipoComp(BigInteger value) {
            this.tipoComp = value;
        }

        /**
         * Gets the value of the rsmnData property.
         * 
         * @return
         *     possible object is
         *     {@link RsmnDataRem }
         *     
         */
        public RsmnDataRem getRsmnData() {
            return rsmnData;
        }

        /**
         * Sets the value of the rsmnData property.
         * 
         * @param value
         *     allowed object is
         *     {@link RsmnDataRem }
         *     
         */
        public void setRsmnData(RsmnDataRem value) {
            this.rsmnData = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TipoComp">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
     *               &lt;enumeration value="281"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Rem_Cont"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipoComp",
        "rsmnData"
    })
    public static class RsmnRemCont {

        @XmlElement(name = "TipoComp", required = true)
        protected BigInteger tipoComp;
        @XmlElement(name = "RsmnData", required = true)
        protected RsmnDataRemCont rsmnData;

        /**
         * Gets the value of the tipoComp property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTipoComp() {
            return tipoComp;
        }

        /**
         * Sets the value of the tipoComp property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTipoComp(BigInteger value) {
            this.tipoComp = value;
        }

        /**
         * Gets the value of the rsmnData property.
         * 
         * @return
         *     possible object is
         *     {@link RsmnDataRemCont }
         *     
         */
        public RsmnDataRemCont getRsmnData() {
            return rsmnData;
        }

        /**
         * Sets the value of the rsmnData property.
         * 
         * @param value
         *     allowed object is
         *     {@link RsmnDataRemCont }
         *     
         */
        public void setRsmnData(RsmnDataRemCont value) {
            this.rsmnData = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TipoComp">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
     *               &lt;enumeration value="182"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Resg"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipoComp",
        "rsmnData"
    })
    public static class RsmnResg {

        @XmlElement(name = "TipoComp", required = true)
        protected BigInteger tipoComp;
        @XmlElement(name = "RsmnData", required = true)
        protected RsmnDataResg rsmnData;

        /**
         * Gets the value of the tipoComp property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTipoComp() {
            return tipoComp;
        }

        /**
         * Sets the value of the tipoComp property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTipoComp(BigInteger value) {
            this.tipoComp = value;
        }

        /**
         * Gets the value of the rsmnData property.
         * 
         * @return
         *     possible object is
         *     {@link RsmnDataResg }
         *     
         */
        public RsmnDataResg getRsmnData() {
            return rsmnData;
        }

        /**
         * Sets the value of the rsmnData property.
         * 
         * @param value
         *     allowed object is
         *     {@link RsmnDataResg }
         *     
         */
        public void setRsmnData(RsmnDataResg value) {
            this.rsmnData = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TipoComp">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
     *               &lt;enumeration value="282"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Resg_Cont"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipoComp",
        "rsmnData"
    })
    public static class RsmnResgCont {

        @XmlElement(name = "TipoComp", required = true)
        protected BigInteger tipoComp;
        @XmlElement(name = "RsmnData", required = true)
        protected RsmnDataResgCont rsmnData;

        /**
         * Gets the value of the tipoComp property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTipoComp() {
            return tipoComp;
        }

        /**
         * Sets the value of the tipoComp property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTipoComp(BigInteger value) {
            this.tipoComp = value;
        }

        /**
         * Gets the value of the rsmnData property.
         * 
         * @return
         *     possible object is
         *     {@link RsmnDataResgCont }
         *     
         */
        public RsmnDataResgCont getRsmnData() {
            return rsmnData;
        }

        /**
         * Sets the value of the rsmnData property.
         * 
         * @param value
         *     allowed object is
         *     {@link RsmnDataResgCont }
         *     
         */
        public void setRsmnData(RsmnDataResgCont value) {
            this.rsmnData = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TipoComp">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
     *               &lt;enumeration value="101"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Tck"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipoComp",
        "rsmnData"
    })
    public static class RsmnTck {

        @XmlElement(name = "TipoComp", required = true)
        protected BigInteger tipoComp;
        @XmlElement(name = "RsmnData", required = true)
        protected RsmnDataTck rsmnData;

        /**
         * Gets the value of the tipoComp property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTipoComp() {
            return tipoComp;
        }

        /**
         * Sets the value of the tipoComp property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTipoComp(BigInteger value) {
            this.tipoComp = value;
        }

        /**
         * Gets the value of the rsmnData property.
         * 
         * @return
         *     possible object is
         *     {@link RsmnDataTck }
         *     
         */
        public RsmnDataTck getRsmnData() {
            return rsmnData;
        }

        /**
         * Sets the value of the rsmnData property.
         * 
         * @param value
         *     allowed object is
         *     {@link RsmnDataTck }
         *     
         */
        public void setRsmnData(RsmnDataTck value) {
            this.rsmnData = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TipoComp">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
     *               &lt;enumeration value="201"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Tck_Cont"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipoComp",
        "rsmnData"
    })
    public static class RsmnTckCont {

        @XmlElement(name = "TipoComp", required = true)
        protected BigInteger tipoComp;
        @XmlElement(name = "RsmnData", required = true)
        protected RsmnDataTckCont rsmnData;

        /**
         * Gets the value of the tipoComp property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTipoComp() {
            return tipoComp;
        }

        /**
         * Sets the value of the tipoComp property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTipoComp(BigInteger value) {
            this.tipoComp = value;
        }

        /**
         * Gets the value of the rsmnData property.
         * 
         * @return
         *     possible object is
         *     {@link RsmnDataTckCont }
         *     
         */
        public RsmnDataTckCont getRsmnData() {
            return rsmnData;
        }

        /**
         * Sets the value of the rsmnData property.
         * 
         * @param value
         *     allowed object is
         *     {@link RsmnDataTckCont }
         *     
         */
        public void setRsmnData(RsmnDataTckCont value) {
            this.rsmnData = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TipoComp">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
     *               &lt;enumeration value="202"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Tck_Cont"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipoComp",
        "rsmnData"
    })
    public static class RsmnTckContNotaCredito {

        @XmlElement(name = "TipoComp", required = true)
        protected BigInteger tipoComp;
        @XmlElement(name = "RsmnData", required = true)
        protected RsmnDataTckCont rsmnData;

        /**
         * Gets the value of the tipoComp property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTipoComp() {
            return tipoComp;
        }

        /**
         * Sets the value of the tipoComp property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTipoComp(BigInteger value) {
            this.tipoComp = value;
        }

        /**
         * Gets the value of the rsmnData property.
         * 
         * @return
         *     possible object is
         *     {@link RsmnDataTckCont }
         *     
         */
        public RsmnDataTckCont getRsmnData() {
            return rsmnData;
        }

        /**
         * Sets the value of the rsmnData property.
         * 
         * @param value
         *     allowed object is
         *     {@link RsmnDataTckCont }
         *     
         */
        public void setRsmnData(RsmnDataTckCont value) {
            this.rsmnData = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TipoComp">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
     *               &lt;enumeration value="203"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Tck_Cont"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipoComp",
        "rsmnData"
    })
    public static class RsmnTckContNotaDebito {

        @XmlElement(name = "TipoComp", required = true)
        protected BigInteger tipoComp;
        @XmlElement(name = "RsmnData", required = true)
        protected RsmnDataTckCont rsmnData;

        /**
         * Gets the value of the tipoComp property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTipoComp() {
            return tipoComp;
        }

        /**
         * Sets the value of the tipoComp property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTipoComp(BigInteger value) {
            this.tipoComp = value;
        }

        /**
         * Gets the value of the rsmnData property.
         * 
         * @return
         *     possible object is
         *     {@link RsmnDataTckCont }
         *     
         */
        public RsmnDataTckCont getRsmnData() {
            return rsmnData;
        }

        /**
         * Sets the value of the rsmnData property.
         * 
         * @param value
         *     allowed object is
         *     {@link RsmnDataTckCont }
         *     
         */
        public void setRsmnData(RsmnDataTckCont value) {
            this.rsmnData = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TipoComp">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
     *               &lt;enumeration value="102"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Tck"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipoComp",
        "rsmnData"
    })
    public static class RsmnTckNotaCredito {

        @XmlElement(name = "TipoComp", required = true)
        protected BigInteger tipoComp;
        @XmlElement(name = "RsmnData", required = true)
        protected RsmnDataTck rsmnData;

        /**
         * Gets the value of the tipoComp property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTipoComp() {
            return tipoComp;
        }

        /**
         * Sets the value of the tipoComp property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTipoComp(BigInteger value) {
            this.tipoComp = value;
        }

        /**
         * Gets the value of the rsmnData property.
         * 
         * @return
         *     possible object is
         *     {@link RsmnDataTck }
         *     
         */
        public RsmnDataTck getRsmnData() {
            return rsmnData;
        }

        /**
         * Sets the value of the rsmnData property.
         * 
         * @param value
         *     allowed object is
         *     {@link RsmnDataTck }
         *     
         */
        public void setRsmnData(RsmnDataTck value) {
            this.rsmnData = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TipoComp">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://cfe.dgi.gub.uy}CFEType">
     *               &lt;enumeration value="103"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RsmnData" type="{http://cfe.dgi.gub.uy}RsmnData_Tck"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipoComp",
        "rsmnData"
    })
    public static class RsmnTckNotaDebito {

        @XmlElement(name = "TipoComp", required = true)
        protected BigInteger tipoComp;
        @XmlElement(name = "RsmnData", required = true)
        protected RsmnDataTck rsmnData;

        /**
         * Gets the value of the tipoComp property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTipoComp() {
            return tipoComp;
        }

        /**
         * Sets the value of the tipoComp property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTipoComp(BigInteger value) {
            this.tipoComp = value;
        }

        /**
         * Gets the value of the rsmnData property.
         * 
         * @return
         *     possible object is
         *     {@link RsmnDataTck }
         *     
         */
        public RsmnDataTck getRsmnData() {
            return rsmnData;
        }

        /**
         * Sets the value of the rsmnData property.
         * 
         * @param value
         *     allowed object is
         *     {@link RsmnDataTck }
         *     
         */
        public void setRsmnData(RsmnDataTck value) {
            this.rsmnData = value;
        }

    }

}
