//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.22 at 04:42:09 PM UYST 
//


package uy.gub.dgi.cfe;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MotivoRechazoCFEType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MotivoRechazoCFEType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="A02"/>
 *     &lt;enumeration value="E01"/>
 *     &lt;enumeration value="E02"/>
 *     &lt;enumeration value="E03"/>
 *     &lt;enumeration value="E04"/>
 *     &lt;enumeration value="E05"/>
 *     &lt;enumeration value="E06"/>
 *     &lt;enumeration value="E07"/>
 *     &lt;enumeration value="E08"/>
 *     &lt;enumeration value="E20"/>
 *     &lt;enumeration value="E21"/>
 *     &lt;enumeration value="E22"/>
 *     &lt;enumeration value="E23"/>
 *     &lt;enumeration value="E24"/>
 *     &lt;enumeration value="E25"/>
 *     &lt;enumeration value="E26"/>
 *     &lt;enumeration value="E27"/>
 *     &lt;enumeration value="E28"/>
 *     &lt;enumeration value="E29"/>
 *     &lt;enumeration value="E30"/>
 *     &lt;enumeration value="C01"/>
 *     &lt;enumeration value="C02"/>
 *     &lt;enumeration value="C03"/>
 *     &lt;enumeration value="C04"/>
 *     &lt;enumeration value="C05"/>
 *     &lt;enumeration value="C06"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MotivoRechazoCFEType")
@XmlEnum
public enum MotivoRechazoCFEType {

    @XmlEnumValue("A02")
    A_02("A02"),
    @XmlEnumValue("E01")
    E_01("E01"),
    @XmlEnumValue("E02")
    E_02("E02"),
    @XmlEnumValue("E03")
    E_03("E03"),
    @XmlEnumValue("E04")
    E_04("E04"),
    @XmlEnumValue("E05")
    E_05("E05"),
    @XmlEnumValue("E06")
    E_06("E06"),
    @XmlEnumValue("E07")
    E_07("E07"),
    @XmlEnumValue("E08")
    E_08("E08"),
    @XmlEnumValue("E20")
    E_20("E20"),
    @XmlEnumValue("E21")
    E_21("E21"),
    @XmlEnumValue("E22")
    E_22("E22"),
    @XmlEnumValue("E23")
    E_23("E23"),
    @XmlEnumValue("E24")
    E_24("E24"),
    @XmlEnumValue("E25")
    E_25("E25"),
    @XmlEnumValue("E26")
    E_26("E26"),
    @XmlEnumValue("E27")
    E_27("E27"),
    @XmlEnumValue("E28")
    E_28("E28"),
    @XmlEnumValue("E29")
    E_29("E29"),
    @XmlEnumValue("E30")
    E_30("E30"),
    @XmlEnumValue("C01")
    C_01("C01"),
    @XmlEnumValue("C02")
    C_02("C02"),
    @XmlEnumValue("C03")
    C_03("C03"),
    @XmlEnumValue("C04")
    C_04("C04"),
    @XmlEnumValue("C05")
    C_05("C05"),
    @XmlEnumValue("C06")
    C_06("C06");
    private final String value;

    MotivoRechazoCFEType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MotivoRechazoCFEType fromValue(String v) {
        for (MotivoRechazoCFEType c: MotivoRechazoCFEType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
