//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.22 at 04:42:09 PM UYST 
//


package uy.gub.dgi.cfe;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uy.gub.dgi.cfe package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ACKCFE_QNAME = new QName("http://cfe.dgi.gub.uy", "ACKCFE");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uy.gub.dgi.cfe
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ACKCFEdefType }
     * 
     */
    public ACKCFEdefType createACKCFEdefType() {
        return new ACKCFEdefType();
    }

    /**
     * Create an instance of {@link RechazoSobreType }
     * 
     */
    public RechazoSobreType createRechazoSobreType() {
        return new RechazoSobreType();
    }

    /**
     * Create an instance of {@link RechazoRepType }
     * 
     */
    public RechazoRepType createRechazoRepType() {
        return new RechazoRepType();
    }

    /**
     * Create an instance of {@link ObsCFCType }
     * 
     */
    public ObsCFCType createObsCFCType() {
        return new ObsCFCType();
    }

    /**
     * Create an instance of {@link RechazoCFEDGIType }
     * 
     */
    public RechazoCFEDGIType createRechazoCFEDGIType() {
        return new RechazoCFEDGIType();
    }

    /**
     * Create an instance of {@link RechazoCFEPartesType }
     * 
     */
    public RechazoCFEPartesType createRechazoCFEPartesType() {
        return new RechazoCFEPartesType();
    }

    /**
     * Create an instance of {@link ACKCFEdefType.Caratula }
     * 
     */
    public ACKCFEdefType.Caratula createACKCFEdefTypeCaratula() {
        return new ACKCFEdefType.Caratula();
    }

    /**
     * Create an instance of {@link ACKCFEdefType.ACKCFEDet }
     * 
     */
    public ACKCFEdefType.ACKCFEDet createACKCFEdefTypeACKCFEDet() {
        return new ACKCFEdefType.ACKCFEDet();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ACKCFEdefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cfe.dgi.gub.uy", name = "ACKCFE")
    public JAXBElement<ACKCFEdefType> createACKCFE(ACKCFEdefType value) {
        return new JAXBElement<ACKCFEdefType>(_ACKCFE_QNAME, ACKCFEdefType.class, null, value);
    }

}
