
package org.example.efactura_x;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import uy.gub.dgi.cfe.CFEDefTypeX;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "efactura_x", targetNamespace = "http://www.example.org/efactura_x/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    uy.gub.dgi.cfe.ObjectFactory.class,
    org.example.efactura_x.ObjectFactory.class,
    org.w3._2000._09.xmldsig.ObjectFactory.class
})
public interface EfacturaX {


    /**
     * 
     * @param parameters
     * @return
     *     returns org.example.efactura_x.OutGenerarCFE
     */
    @WebMethod(action = "http://www.example.org/efactura_x/generarCFE")
    @WebResult(name = "output_generarCFE", targetNamespace = "http://www.example.org/efactura_x/", partName = "parameters")
    public OutGenerarCFE generarCFE(
        @WebParam(name = "cfe_x", targetNamespace = "http://www.example.org/efactura_x/", partName = "parameters")
        CFEDefTypeX parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.example.efactura_x.OutGenerarCFEs
     */
    @WebMethod(action = "http://www.example.org/efactura_x/generarCFE")
    @WebResult(name = "output_generarCFEs", targetNamespace = "http://www.example.org/efactura_x/", partName = "parameters")
    public OutGenerarCFEs generarCFEs(
        @WebParam(name = "lista", targetNamespace = "http://www.example.org/efactura_x/", partName = "parameters")
        ListaCFEX parameters);

}
