
package org.example.efactura_x;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "efactura_x", targetNamespace = "http://www.example.org/efactura_x/", wsdlLocation = "file:/C:/Users/d0178/workspace/EFacturaWeb/src/xg/efactura_x.wsdl")
public class EfacturaX_Service
    extends Service
{

    private final static URL EFACTURAX_WSDL_LOCATION;
    private final static WebServiceException EFACTURAX_EXCEPTION;
    private final static QName EFACTURAX_QNAME = new QName("http://www.example.org/efactura_x/", "efactura_x");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/d0178/workspace/EFacturaWeb/src/xg/efactura_x.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EFACTURAX_WSDL_LOCATION = url;
        EFACTURAX_EXCEPTION = e;
    }

    public EfacturaX_Service() {
        super(__getWsdlLocation(), EFACTURAX_QNAME);
    }

    public EfacturaX_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), EFACTURAX_QNAME, features);
    }

    public EfacturaX_Service(URL wsdlLocation) {
        super(wsdlLocation, EFACTURAX_QNAME);
    }

    public EfacturaX_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EFACTURAX_QNAME, features);
    }

    public EfacturaX_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EfacturaX_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EfacturaX
     */
    @WebEndpoint(name = "efactura_xSOAP")
    public EfacturaX getEfacturaXSOAP() {
        return super.getPort(new QName("http://www.example.org/efactura_x/", "efactura_xSOAP"), EfacturaX.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EfacturaX
     */
    @WebEndpoint(name = "efactura_xSOAP")
    public EfacturaX getEfacturaXSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/efactura_x/", "efactura_xSOAP"), EfacturaX.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EFACTURAX_EXCEPTION!= null) {
            throw EFACTURAX_EXCEPTION;
        }
        return EFACTURAX_WSDL_LOCATION;
    }

}
